extends Node

const TileSize = 64 # 网格大小

# 当前选中的关卡ID（由 level_select 点击时设置，map 读取后加载对应场景）
var currentStageId: int = 0

## 各关卡启用的能力技能（key = 关卡 id，值 = 技能 id 数组，顺序即技能条显示顺序）
## 技能 id 定义见 autoload/ability_manager.gd 的 ABILITIES
## 没有列在这里的关卡不会显示技能条
const stageAbilities := {
	0: ["bombard", "invincible"], # 教程：显示全部
	2: ["bombard"],
	3: ["invincible"],
	4: ["bombard", "invincible"],
	5: ["bombard"],
	6: ["invincible"],
	7: ["bombard", "invincible"],
	8: ["bombard"],
	9: ["invincible"],
	10: ["bombard", "invincible"],
	11: ["bombard"],
	12: ["invincible"],
	13: ["bombard", "invincible"],
	14: ["bombard", "invincible"],
	15: ["bombard", "invincible"],
}


# 取某关卡启用的能力技能；未配置的关卡返回空数组（不显示技能条）
func getAbilities(stage_id: int) -> Array:
	return stageAbilities.get(stage_id, [])


## 各关卡**允许建造**的防御塔（key = 关卡 id，值 = 塔类型数组）
## 没有列在这里的关卡 = 不限制（tower_ui 会显示全部 7 座）
## 想放开某关就从这张表里删掉它，或补上缺的塔类型
var stageTowers := {
	#0: [Game.towerType.machineGunTower, Game.towerType.cannonTower, Game.towerType.rocketTower],
	1: [Game.towerType.machineGunTower, Game.towerType.cannonTower, Game.towerType.rocketTower],
	2: [Game.towerType.machineGunTower, Game.towerType.cannonTower, Game.towerType.rocketTower,
		Game.towerType.EMPTower],
	3: [Game.towerType.machineGunTower, Game.towerType.cannonTower, Game.towerType.rocketTower,
		Game.towerType.EMPTower, Game.towerType.teslaCoilTower],
	4: [Game.towerType.machineGunTower, Game.towerType.cannonTower, Game.towerType.rocketTower,
		Game.towerType.EMPTower, Game.towerType.teslaCoilTower, Game.towerType.laserTower],
	# 5 关及以后不配置 = 全部可建
}

# 取某关卡允许建造的塔；返回空数组表示「不限制」
func getTowers(stage_id: int) -> Array:
	return stageTowers.get(stage_id, [])

# 该关卡是否允许建造某种塔
func isTowerAllowed(stage_id: int, tower_type) -> bool:
	var allowed: Array = getTowers(stage_id)
	if allowed.is_empty():
		return true
	return tower_type in allowed


## 某关卡声明的路线数（默认 1）。
## 真正的路线节点在关卡场景里 —— 场景里按顺序摆几个 Path2D 就有几条路线。
## 这个字段是给 UI / 一致性校验用的声明值，两边对不上时 base_level 会 push_warning。
func getRouteCount(stage_id: int) -> int:
	for s in allStage:
		if int(s.get("id", -1)) == stage_id:
			return maxi(1, int(s.get("routes", 1)))
	return 1


#关卡的数据
#
# enemySpawner 里每一条的写法：
#     {'time': 波次, 'type': 敌人类型, 'number': 数量}
#     {'time': 波次, 'type': 敌人类型, 'number': 数量, 'route': 路线号}   # 可选
#     {'time': 波次, 'type': 敌人类型, 'number': 数量, 'offset': 出发偏移}  # 可选，可与 route 同写
#
# 'route' 不写 = 从**路线1**出发；写 2、3 …… 就从对应路线出发。
# 路线号从 1 开始，对应关卡场景里 Path2D 的摆放顺序（第 1 个 Path2D 就是路线1）。
# 单路线关卡里写 'route': 2 不会出错，会自动回落到最后一条路线。
#
# 'offset' 不写 = 0（敌人贴着路线中线走）。
# 有些关卡的路线两边各压着一条传送带，中线正好落在两条带子中间，敌人看着就"错位"；
# 给一个**固定**的偏移（±32 = 半个格子，正好对到带子中线上）就能整条路都贴住其中一条。
# 单位：像素；正数 = **行进方向的右侧**，负数 = 左侧。偏移算在路线自己的坐标系里
# （PathFollow2D 的 v_offset），所以拐弯时会跟着一起拐，始终平行于中线。
# 想让同一波的敌人分走两条带子，就写两条 time 相同、offset 相反、route 相同的记录。
var allStage = [
	{
		'name': 'Tutorial',
		"id": 0,
		'routes': 1,   # 本关路线数（和场景里 Path2D 的数量对应）
		"gemReward": 3,
		'selectable': false,
		'type': '工厂',
		'category': '厂前空地',
		'description': '厂前空地。教程关卡，单向直线，逐一认识各类敌人的威胁与节奏',
		'wave': 10,
		'health': 25,
		'money': 1200,
		'scene': 'res://scene/level/level_tutorial.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.miniTank, 'number': 1},
			{'time': 2, 'type': Game.enemyType.mediumTank, 'number': 1},
			{'time': 3, 'type': Game.enemyType.heavyTank, 'number': 1},
			{'time': 4, 'type': Game.enemyType.armoredTank, 'number': 1},
			{'time': 5, 'type': Game.enemyType.assaultBuggy, 'number': 1},
			{'time': 6, 'type': Game.enemyType.medic, 'number': 1},
			{'time': 7, 'type': Game.enemyType.suicideTruck, 'number': 1},
			{'time': 8, 'type': Game.enemyType.missileTruck, 'number': 1},
			{'time': 9, 'type': Game.enemyType.scoutDrone, 'number': 1},
			{'time': 10, 'type': Game.enemyType.attackHelicopter, 'number': 1}
		]
	},
	{
		'name': '1',
		"id": 1,
		'routes': 2,   # 本关路线数（和场景里 Path2D 的数量对应）
		"gemReward": 5,
		'type': '工厂',
		'category': '厂区大门',
		'description': '敌人从厂区正门涌入，路线开阔，适合熟悉防守节奏',
		'wave': 3,
		'health': 20,
		'money': 150,
		'scene': 'res://scene/level/level_1.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.miniTank, 'number': 1, 'route': 1},
			{'time': 1, 'type': Game.enemyType.miniTank, 'number': 1, 'route': 2},
			{'time': 2, 'type': Game.enemyType.miniTank, 'number': 2, 'route': 1},
			{'time': 2, 'type': Game.enemyType.miniTank, 'number': 1, 'route': 2},
			{'time': 3, 'type': Game.enemyType.miniTank, 'number': 2, 'route': 1},
			{'time': 3, 'type': Game.enemyType.miniTank, 'number': 2, 'route': 2}
		]
	},
	{
		'name': '2',
		"id": 2,
		'routes': 2,   # 本关路线数（和场景里 Path2D 的数量对应）
		"gemReward": 6,
		'type': '工厂',
		'category': '门岗与装卸区',
		'description': '装卸区通道变宽，敌人开始成群从正门压上',
		'wave': 5,
		'health': 18,
		'money': 200,
		'scene': 'res://scene/level/level_2.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.miniTank, 'number': 2, 'route': 1},
			{'time': 1, 'type': Game.enemyType.miniTank, 'number': 1, 'route': 2},
			{'time': 2, 'type': Game.enemyType.miniTank, 'number': 2, 'route': 1},
			{'time': 2, 'type': Game.enemyType.miniTank, 'number': 2, 'route': 2},
			{'time': 2, 'type': Game.enemyType.assaultBuggy, 'number': 1, 'route': 1},
			{'time': 2, 'type': Game.enemyType.assaultBuggy, 'number': 1, 'route': 2},
			{'time': 3, 'type': Game.enemyType.miniTank, 'number': 3, 'route': 1},
			{'time': 3, 'type': Game.enemyType.miniTank, 'number': 2, 'route': 2},
			{'time': 3, 'type': Game.enemyType.assaultBuggy, 'number': 1, 'route': 1},
			{'time': 3, 'type': Game.enemyType.assaultBuggy, 'number': 1, 'route': 2},
			{'time': 4, 'type': Game.enemyType.miniTank, 'number': 3, 'route': 1},
			{'time': 4, 'type': Game.enemyType.miniTank, 'number': 3, 'route': 2},
			{'time': 4, 'type': Game.enemyType.assaultBuggy, 'number': 2, 'route': 1},
			{'time': 4, 'type': Game.enemyType.assaultBuggy, 'number': 1, 'route': 2},
			{'time': 5, 'type': Game.enemyType.mediumTank, 'number': 1, 'route': 1},
			{'time': 5, 'type': Game.enemyType.assaultBuggy, 'number': 2, 'route': 1},
			{'time': 5, 'type': Game.enemyType.assaultBuggy, 'number': 2, 'route': 2}
		]
	},
	{
		'name': '3',
		"id": 3,
		'routes': 2,   # 本关路线数（和场景里 Path2D 的数量对应）
		"gemReward": 7,
		'type': '工厂',
		'category': '原料堆场',
		'description': '原料堆场道路收窄，第一次出现重型目标',
		'wave': 5,
		'health': 18,
		'money': 220,
		'scene': 'res://scene/level/level_3.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.miniTank, 'number': 2, 'route': 1},
			{'time': 1, 'type': Game.enemyType.miniTank, 'number': 2, 'route': 2},
			{'time': 2, 'type': Game.enemyType.miniTank, 'number': 3, 'route': 1},
			{'time': 2, 'type': Game.enemyType.miniTank, 'number': 2, 'route': 2},
			{'time': 2, 'type': Game.enemyType.mediumTank, 'number': 1, 'route': 1},
			{'time': 3, 'type': Game.enemyType.miniTank, 'number': 3, 'route': 1},
			{'time': 3, 'type': Game.enemyType.miniTank, 'number': 3, 'route': 2},
			{'time': 3, 'type': Game.enemyType.mediumTank, 'number': 1, 'route': 2},
			{'time': 4, 'type': Game.enemyType.assaultBuggy, 'number': 2, 'route': 1},
			{'time': 4, 'type': Game.enemyType.assaultBuggy, 'number': 1, 'route': 2},
			{'time': 4, 'type': Game.enemyType.mediumTank, 'number': 1, 'route': 1},
			{'time': 4, 'type': Game.enemyType.mediumTank, 'number': 1, 'route': 2},
			{'time': 5, 'type': Game.enemyType.heavyTank, 'number': 1, 'route': 1}
		]
	},
	{
		'name': '4',
		"id": 4,
		'routes': 2,   # 本关路线数（和场景里 Path2D 的数量对应）
		"gemReward": 8,
		'type': '工厂',
		'category': '一号传送带',
		'description': '沿一号传送带布防，转角增多，自爆车开始出现',
		'wave': 7,
		'health': 16,
		'money': 190,
		'scene': 'res://scene/level/level_4.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.assaultBuggy, 'number': 3, 'route': 1},
			{'time': 1, 'type': Game.enemyType.assaultBuggy, 'number': 2, 'route': 2},
			{'time': 1, 'type': Game.enemyType.miniTank, 'number': 2, 'route': 1},
			{'time': 1, 'type': Game.enemyType.miniTank, 'number': 2, 'route': 2},
			{'time': 2, 'type': Game.enemyType.assaultBuggy, 'number': 4, 'route': 1},
			{'time': 2, 'type': Game.enemyType.assaultBuggy, 'number': 3, 'route': 2},
			{'time': 2, 'type': Game.enemyType.mediumTank, 'number': 1, 'route': 1},
			{'time': 3, 'type': Game.enemyType.miniTank, 'number': 5, 'route': 1},
			{'time': 3, 'type': Game.enemyType.miniTank, 'number': 5, 'route': 2},
			{'time': 3, 'type': Game.enemyType.mediumTank, 'number': 1, 'route': 1},
			{'time': 3, 'type': Game.enemyType.mediumTank, 'number': 1, 'route': 2},
			{'time': 4, 'type': Game.enemyType.suicideTruck, 'number': 1, 'route': 2},
			{'time': 4, 'type': Game.enemyType.assaultBuggy, 'number': 4, 'route': 1},
			{'time': 4, 'type': Game.enemyType.assaultBuggy, 'number': 4, 'route': 2},
			{'time': 5, 'type': Game.enemyType.heavyTank, 'number': 1, 'route': 1},
			{'time': 5, 'type': Game.enemyType.heavyTank, 'number': 1, 'route': 2},
			{'time': 5, 'type': Game.enemyType.assaultBuggy, 'number': 3, 'route': 1},
			{'time': 5, 'type': Game.enemyType.assaultBuggy, 'number': 3, 'route': 2},
			{'time': 6, 'type': Game.enemyType.suicideTruck, 'number': 1, 'route': 1},
			{'time': 6, 'type': Game.enemyType.suicideTruck, 'number': 1, 'route': 2},
			{'time': 6, 'type': Game.enemyType.mediumTank, 'number': 2, 'route': 1},
			{'time': 6, 'type': Game.enemyType.mediumTank, 'number': 1, 'route': 2},
			{'time': 7, 'type': Game.enemyType.heavyTank, 'number': 1, 'route': 1},
			{'time': 7, 'type': Game.enemyType.heavyTank, 'number': 1, 'route': 2},
			{'time': 7, 'type': Game.enemyType.assaultBuggy, 'number': 5, 'route': 1},
			{'time': 7, 'type': Game.enemyType.assaultBuggy, 'number': 5, 'route': 2}
		]
	},
	{
		'name': '5',
		"id": 5,
		'routes': 2,   # 本关路线数（和场景里 Path2D 的数量对应）
		"gemReward": 9,
		'type': '工厂',
		'category': '装配车间',
		'description': '进入装配车间，夹道更长，导弹车首次登场',
		'wave': 8,
		'health': 14,
		'money': 230,
		'scene': 'res://scene/level/level_5.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.miniTank, 'number': 3, 'route': 1},
			{'time': 1, 'type': Game.enemyType.miniTank, 'number': 3, 'route': 2},
			{'time': 1, 'type': Game.enemyType.mediumTank, 'number': 1, 'route': 1},
			{'time': 2, 'type': Game.enemyType.missileTruck, 'number': 1, 'route': 2},
			{'time': 2, 'type': Game.enemyType.assaultBuggy, 'number': 3, 'route': 1},
			{'time': 2, 'type': Game.enemyType.assaultBuggy, 'number': 2, 'route': 2},
			{'time': 3, 'type': Game.enemyType.mediumTank, 'number': 2, 'route': 1},
			{'time': 3, 'type': Game.enemyType.mediumTank, 'number': 1, 'route': 2},
			{'time': 3, 'type': Game.enemyType.miniTank, 'number': 4, 'route': 1},
			{'time': 3, 'type': Game.enemyType.miniTank, 'number': 4, 'route': 2},
			{'time': 4, 'type': Game.enemyType.missileTruck, 'number': 1, 'route': 1},
			{'time': 4, 'type': Game.enemyType.heavyTank, 'number': 1, 'route': 2},
			{'time': 5, 'type': Game.enemyType.mediumTank, 'number': 2, 'route': 1},
			{'time': 5, 'type': Game.enemyType.mediumTank, 'number': 2, 'route': 2},
			{'time': 5, 'type': Game.enemyType.assaultBuggy, 'number': 4, 'route': 1},
			{'time': 5, 'type': Game.enemyType.assaultBuggy, 'number': 4, 'route': 2},
			{'time': 6, 'type': Game.enemyType.missileTruck, 'number': 1, 'route': 1},
			{'time': 6, 'type': Game.enemyType.missileTruck, 'number': 1, 'route': 2},
			{'time': 6, 'type': Game.enemyType.heavyTank, 'number': 1, 'route': 1},
			{'time': 6, 'type': Game.enemyType.heavyTank, 'number': 1, 'route': 2},
			{'time': 7, 'type': Game.enemyType.suicideTruck, 'number': 1, 'route': 1},
			{'time': 7, 'type': Game.enemyType.suicideTruck, 'number': 1, 'route': 2},
			{'time': 7, 'type': Game.enemyType.mediumTank, 'number': 3, 'route': 1},
			{'time': 7, 'type': Game.enemyType.mediumTank, 'number': 2, 'route': 2},
			{'time': 8, 'type': Game.enemyType.missileTruck, 'number': 1, 'route': 1},
			{'time': 8, 'type': Game.enemyType.missileTruck, 'number': 1, 'route': 2},
			{'time': 8, 'type': Game.enemyType.heavyTank, 'number': 2, 'route': 1},
			{'time': 8, 'type': Game.enemyType.heavyTank, 'number': 1, 'route': 2}
		]
	},
	{
		'name': '6',
		"id": 6,
		'routes': 2,   # 本关路线数（和场景里 Path2D 的数量对应）
		"gemReward": 10,
		'type': '工厂',
		'category': '焊接车间',
		'description': '焊接车间内通道交错，空中与地面单位混合来袭',
		'wave': 9,
		'health': 12,
		'money': 280,
		'scene': 'res://scene/level/level_6.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.assaultBuggy, 'number': 3, 'route': 1},
			{'time': 1, 'type': Game.enemyType.assaultBuggy, 'number': 3, 'route': 2},
			{'time': 1, 'type': Game.enemyType.scoutDrone, 'number': 1, 'route': 1},
			{'time': 1, 'type': Game.enemyType.scoutDrone, 'number': 1, 'route': 2},
			{'time': 2, 'type': Game.enemyType.miniTank, 'number': 4, 'route': 1},
			{'time': 2, 'type': Game.enemyType.miniTank, 'number': 4, 'route': 2},
			{'time': 2, 'type': Game.enemyType.mediumTank, 'number': 1, 'route': 1},
			{'time': 2, 'type': Game.enemyType.mediumTank, 'number': 1, 'route': 2},
			{'time': 3, 'type': Game.enemyType.attackHelicopter, 'number': 1, 'route': 1},
			{'time': 3, 'type': Game.enemyType.assaultBuggy, 'number': 4, 'route': 1},
			{'time': 3, 'type': Game.enemyType.assaultBuggy, 'number': 4, 'route': 2},
			{'time': 4, 'type': Game.enemyType.missileTruck, 'number': 1, 'route': 2},
			{'time': 4, 'type': Game.enemyType.heavyTank, 'number': 1, 'route': 1},
			{'time': 4, 'type': Game.enemyType.heavyTank, 'number': 1, 'route': 2},
			{'time': 5, 'type': Game.enemyType.attackHelicopter, 'number': 1, 'route': 1},
			{'time': 5, 'type': Game.enemyType.attackHelicopter, 'number': 1, 'route': 2},
			{'time': 5, 'type': Game.enemyType.mediumTank, 'number': 2, 'route': 1},
			{'time': 5, 'type': Game.enemyType.mediumTank, 'number': 2, 'route': 2},
			{'time': 6, 'type': Game.enemyType.suicideTruck, 'number': 1, 'route': 1},
			{'time': 6, 'type': Game.enemyType.suicideTruck, 'number': 1, 'route': 2},
			{'time': 6, 'type': Game.enemyType.scoutDrone, 'number': 2, 'route': 1},
			{'time': 6, 'type': Game.enemyType.scoutDrone, 'number': 2, 'route': 2},
			{'time': 7, 'type': Game.enemyType.missileTruck, 'number': 1, 'route': 1},
			{'time': 7, 'type': Game.enemyType.missileTruck, 'number': 1, 'route': 2},
			{'time': 7, 'type': Game.enemyType.heavyTank, 'number': 2, 'route': 1},
			{'time': 7, 'type': Game.enemyType.heavyTank, 'number': 1, 'route': 2},
			{'time': 8, 'type': Game.enemyType.attackHelicopter, 'number': 1, 'route': 1},
			{'time': 8, 'type': Game.enemyType.attackHelicopter, 'number': 1, 'route': 2},
			{'time': 8, 'type': Game.enemyType.mediumTank, 'number': 3, 'route': 1},
			{'time': 8, 'type': Game.enemyType.mediumTank, 'number': 2, 'route': 2},
			{'time': 9, 'type': Game.enemyType.missileTruck, 'number': 2, 'route': 1},
			{'time': 9, 'type': Game.enemyType.missileTruck, 'number': 1, 'route': 2},
			{'time': 9, 'type': Game.enemyType.heavyTank, 'number': 2, 'route': 1},
			{'time': 9, 'type': Game.enemyType.heavyTank, 'number': 2, 'route': 2}
		]
	},
	{
		'name': '7',
		"id": 7,
		'routes': 2,   # 本关路线数（和场景里 Path2D 的数量对应）
		"gemReward": 11,
		'type': '工厂',
		'category': '喷涂车间',
		'description': '喷涂车间纵深更长，敌人密度明显提升',
		'wave': 10,
		'health': 12,
		'money': 320,
		'scene': 'res://scene/level/level_7.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.miniTank, 'number': 4, 'route': 1},
			{'time': 1, 'type': Game.enemyType.miniTank, 'number': 4, 'route': 2},
			{'time': 1, 'type': Game.enemyType.scoutDrone, 'number': 1, 'route': 1},
			{'time': 1, 'type': Game.enemyType.scoutDrone, 'number': 1, 'route': 2},
			{'time': 2, 'type': Game.enemyType.assaultBuggy, 'number': 4, 'route': 1},
			{'time': 2, 'type': Game.enemyType.assaultBuggy, 'number': 4, 'route': 2},
			{'time': 2, 'type': Game.enemyType.mediumTank, 'number': 2, 'route': 1},
			{'time': 2, 'type': Game.enemyType.mediumTank, 'number': 1, 'route': 2},
			{'time': 3, 'type': Game.enemyType.attackHelicopter, 'number': 1, 'route': 1},
			{'time': 3, 'type': Game.enemyType.miniTank, 'number': 5, 'route': 1},
			{'time': 3, 'type': Game.enemyType.miniTank, 'number': 5, 'route': 2},
			{'time': 4, 'type': Game.enemyType.missileTruck, 'number': 1, 'route': 2},
			{'time': 4, 'type': Game.enemyType.assaultBuggy, 'number': 5, 'route': 1},
			{'time': 4, 'type': Game.enemyType.assaultBuggy, 'number': 5, 'route': 2},
			{'time': 5, 'type': Game.enemyType.heavyTank, 'number': 1, 'route': 1},
			{'time': 5, 'type': Game.enemyType.heavyTank, 'number': 1, 'route': 2},
			{'time': 5, 'type': Game.enemyType.mediumTank, 'number': 2, 'route': 1},
			{'time': 5, 'type': Game.enemyType.mediumTank, 'number': 2, 'route': 2},
			{'time': 6, 'type': Game.enemyType.attackHelicopter, 'number': 1, 'route': 1},
			{'time': 6, 'type': Game.enemyType.attackHelicopter, 'number': 1, 'route': 2},
			{'time': 6, 'type': Game.enemyType.scoutDrone, 'number': 2, 'route': 1},
			{'time': 6, 'type': Game.enemyType.scoutDrone, 'number': 2, 'route': 2},
			{'time': 7, 'type': Game.enemyType.suicideTruck, 'number': 1, 'route': 1},
			{'time': 7, 'type': Game.enemyType.suicideTruck, 'number': 1, 'route': 2},
			{'time': 7, 'type': Game.enemyType.missileTruck, 'number': 1, 'route': 1},
			{'time': 7, 'type': Game.enemyType.missileTruck, 'number': 1, 'route': 2},
			{'time': 8, 'type': Game.enemyType.heavyTank, 'number': 2, 'route': 1},
			{'time': 8, 'type': Game.enemyType.heavyTank, 'number': 1, 'route': 2},
			{'time': 8, 'type': Game.enemyType.assaultBuggy, 'number': 6, 'route': 1},
			{'time': 8, 'type': Game.enemyType.assaultBuggy, 'number': 6, 'route': 2},
			{'time': 9, 'type': Game.enemyType.attackHelicopter, 'number': 1, 'route': 1},
			{'time': 9, 'type': Game.enemyType.attackHelicopter, 'number': 1, 'route': 2},
			{'time': 10, 'type': Game.enemyType.missileTruck, 'number': 2, 'route': 1},
			{'time': 10, 'type': Game.enemyType.missileTruck, 'number': 1, 'route': 2}
		]
	},
	{
		'name': '8',
		"id": 8,
		'routes': 2,   # 本关路线数（和场景里 Path2D 的数量对应）
		"gemReward": 12,
		'type': '工厂',
		'category': '质检线',
		'description': '质检线道路更窄，远程与空中单位密度提高',
		'wave': 11,
		'health': 11,
		'money': 360,
		'scene': 'res://scene/level/level_8.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.assaultBuggy, 'number': 5, 'route': 1},
			{'time': 1, 'type': Game.enemyType.assaultBuggy, 'number': 5, 'route': 2},
			{'time': 1, 'type': Game.enemyType.mediumTank, 'number': 1, 'route': 1},
			{'time': 1, 'type': Game.enemyType.mediumTank, 'number': 1, 'route': 2},
			{'time': 2, 'type': Game.enemyType.scoutDrone, 'number': 2, 'route': 1},
			{'time': 2, 'type': Game.enemyType.scoutDrone, 'number': 2, 'route': 2},
			{'time': 2, 'type': Game.enemyType.miniTank, 'number': 5, 'route': 1},
			{'time': 2, 'type': Game.enemyType.miniTank, 'number': 5, 'route': 2},
			{'time': 3, 'type': Game.enemyType.heavyTank, 'number': 1, 'route': 1},
			{'time': 3, 'type': Game.enemyType.heavyTank, 'number': 1, 'route': 2},
			{'time': 3, 'type': Game.enemyType.assaultBuggy, 'number': 4, 'route': 1},
			{'time': 3, 'type': Game.enemyType.assaultBuggy, 'number': 4, 'route': 2},
			{'time': 4, 'type': Game.enemyType.missileTruck, 'number': 1, 'route': 1},
			{'time': 4, 'type': Game.enemyType.missileTruck, 'number': 1, 'route': 2},
			{'time': 4, 'type': Game.enemyType.mediumTank, 'number': 2, 'route': 1},
			{'time': 4, 'type': Game.enemyType.mediumTank, 'number': 2, 'route': 2},
			{'time': 5, 'type': Game.enemyType.attackHelicopter, 'number': 1, 'route': 1},
			{'time': 5, 'type': Game.enemyType.attackHelicopter, 'number': 1, 'route': 2},
			{'time': 5, 'type': Game.enemyType.scoutDrone, 'number': 3, 'route': 1},
			{'time': 5, 'type': Game.enemyType.scoutDrone, 'number': 2, 'route': 2},
			{'time': 6, 'type': Game.enemyType.suicideTruck, 'number': 1, 'route': 1},
			{'time': 6, 'type': Game.enemyType.suicideTruck, 'number': 1, 'route': 2},
			{'time': 6, 'type': Game.enemyType.heavyTank, 'number': 2, 'route': 1},
			{'time': 6, 'type': Game.enemyType.heavyTank, 'number': 1, 'route': 2},
			{'time': 7, 'type': Game.enemyType.missileTruck, 'number': 1, 'route': 1},
			{'time': 7, 'type': Game.enemyType.missileTruck, 'number': 1, 'route': 2},
			{'time': 7, 'type': Game.enemyType.attackHelicopter, 'number': 2, 'route': 1},
			{'time': 7, 'type': Game.enemyType.attackHelicopter, 'number': 1, 'route': 2},
			{'time': 8, 'type': Game.enemyType.mediumTank, 'number': 3, 'route': 1},
			{'time': 8, 'type': Game.enemyType.mediumTank, 'number': 2, 'route': 2},
			{'time': 8, 'type': Game.enemyType.assaultBuggy, 'number': 6, 'route': 1},
			{'time': 8, 'type': Game.enemyType.assaultBuggy, 'number': 6, 'route': 2},
			{'time': 9, 'type': Game.enemyType.heavyTank, 'number': 2, 'route': 1},
			{'time': 9, 'type': Game.enemyType.heavyTank, 'number': 2, 'route': 2},
			{'time': 10, 'type': Game.enemyType.suicideTruck, 'number': 2, 'route': 1},
			{'time': 10, 'type': Game.enemyType.suicideTruck, 'number': 1, 'route': 2},
			{'time': 11, 'type': Game.enemyType.missileTruck, 'number': 2, 'route': 1},
			{'time': 11, 'type': Game.enemyType.missileTruck, 'number': 1, 'route': 2}
		]
	},
	{
		'name': '9',
		"id": 9,
		'routes': 2,   # 本关路线数（和场景里 Path2D 的数量对应）
		"gemReward": 13,
		'type': '工厂',
		'category': '成品仓库',
		'description': '成品仓库高数量敌群压境，防线需要持续压制',
		'wave': 12,
		'health': 11,
		'money': 400,
		'scene': 'res://scene/level/level_9.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.miniTank, 'number': 6, 'route': 1},
			{'time': 1, 'type': Game.enemyType.miniTank, 'number': 6, 'route': 2},
			{'time': 1, 'type': Game.enemyType.mediumTank, 'number': 2, 'route': 1},
			{'time': 1, 'type': Game.enemyType.mediumTank, 'number': 1, 'route': 2},
			{'time': 2, 'type': Game.enemyType.missileTruck, 'number': 1, 'route': 1},
			{'time': 2, 'type': Game.enemyType.missileTruck, 'number': 1, 'route': 2},
			{'time': 2, 'type': Game.enemyType.assaultBuggy, 'number': 5, 'route': 1},
			{'time': 2, 'type': Game.enemyType.assaultBuggy, 'number': 5, 'route': 2},
			{'time': 3, 'type': Game.enemyType.heavyTank, 'number': 2, 'route': 1},
			{'time': 3, 'type': Game.enemyType.heavyTank, 'number': 1, 'route': 2},
			{'time': 3, 'type': Game.enemyType.scoutDrone, 'number': 3, 'route': 1},
			{'time': 3, 'type': Game.enemyType.scoutDrone, 'number': 2, 'route': 2},
			{'time': 4, 'type': Game.enemyType.attackHelicopter, 'number': 1, 'route': 1},
			{'time': 4, 'type': Game.enemyType.attackHelicopter, 'number': 1, 'route': 2},
			{'time': 4, 'type': Game.enemyType.mediumTank, 'number': 3, 'route': 1},
			{'time': 4, 'type': Game.enemyType.mediumTank, 'number': 2, 'route': 2},
			{'time': 5, 'type': Game.enemyType.suicideTruck, 'number': 2, 'route': 1},
			{'time': 5, 'type': Game.enemyType.suicideTruck, 'number': 1, 'route': 2},
			{'time': 5, 'type': Game.enemyType.assaultBuggy, 'number': 6, 'route': 1},
			{'time': 5, 'type': Game.enemyType.assaultBuggy, 'number': 6, 'route': 2},
			{'time': 6, 'type': Game.enemyType.missileTruck, 'number': 2, 'route': 1},
			{'time': 6, 'type': Game.enemyType.missileTruck, 'number': 1, 'route': 2},
			{'time': 6, 'type': Game.enemyType.heavyTank, 'number': 2, 'route': 1},
			{'time': 6, 'type': Game.enemyType.heavyTank, 'number': 2, 'route': 2},
			{'time': 7, 'type': Game.enemyType.attackHelicopter, 'number': 2, 'route': 1},
			{'time': 7, 'type': Game.enemyType.attackHelicopter, 'number': 1, 'route': 2},
			{'time': 7, 'type': Game.enemyType.scoutDrone, 'number': 3, 'route': 1},
			{'time': 7, 'type': Game.enemyType.scoutDrone, 'number': 3, 'route': 2},
			{'time': 8, 'type': Game.enemyType.mediumTank, 'number': 3, 'route': 1},
			{'time': 8, 'type': Game.enemyType.mediumTank, 'number': 3, 'route': 2},
			{'time': 8, 'type': Game.enemyType.assaultBuggy, 'number': 7, 'route': 1},
			{'time': 8, 'type': Game.enemyType.assaultBuggy, 'number': 7, 'route': 2},
			{'time': 9, 'type': Game.enemyType.suicideTruck, 'number': 2, 'route': 1},
			{'time': 9, 'type': Game.enemyType.suicideTruck, 'number': 2, 'route': 2},
			{'time': 10, 'type': Game.enemyType.missileTruck, 'number': 2, 'route': 1},
			{'time': 10, 'type': Game.enemyType.missileTruck, 'number': 1, 'route': 2},
			{'time': 11, 'type': Game.enemyType.heavyTank, 'number': 3, 'route': 1},
			{'time': 11, 'type': Game.enemyType.heavyTank, 'number': 2, 'route': 2},
			{'time': 12, 'type': Game.enemyType.attackHelicopter, 'number': 2, 'route': 1},
			{'time': 12, 'type': Game.enemyType.attackHelicopter, 'number': 2, 'route': 2}
		]
	},
	{
		'name': '10',
		"id": 10,
		'routes': 2,   # 本关路线数（和场景里 Path2D 的数量对应）
		"gemReward": 14,
		'type': '工厂',
		'category': '中央控制室',
		'description': '通往中央控制室，综合考验地面、空中与远程防守',
		'wave': 13,
		'health': 10,
		'money': 450,
		'scene': 'res://scene/level/level_10.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.assaultBuggy, 'number': 6, 'route': 1},
			{'time': 1, 'type': Game.enemyType.assaultBuggy, 'number': 6, 'route': 2},
			{'time': 1, 'type': Game.enemyType.scoutDrone, 'number': 2, 'route': 1},
			{'time': 1, 'type': Game.enemyType.scoutDrone, 'number': 2, 'route': 2},
			{'time': 2, 'type': Game.enemyType.mediumTank, 'number': 2, 'route': 1},
			{'time': 2, 'type': Game.enemyType.mediumTank, 'number': 2, 'route': 2},
			{'time': 2, 'type': Game.enemyType.miniTank, 'number': 6, 'route': 1},
			{'time': 2, 'type': Game.enemyType.miniTank, 'number': 6, 'route': 2},
			{'time': 3, 'type': Game.enemyType.missileTruck, 'number': 1, 'route': 1},
			{'time': 3, 'type': Game.enemyType.missileTruck, 'number': 1, 'route': 2},
			{'time': 3, 'type': Game.enemyType.attackHelicopter, 'number': 1, 'route': 1},
			{'time': 3, 'type': Game.enemyType.attackHelicopter, 'number': 1, 'route': 2},
			{'time': 4, 'type': Game.enemyType.heavyTank, 'number': 2, 'route': 1},
			{'time': 4, 'type': Game.enemyType.heavyTank, 'number': 2, 'route': 2},
			{'time': 4, 'type': Game.enemyType.assaultBuggy, 'number': 6, 'route': 1},
			{'time': 4, 'type': Game.enemyType.assaultBuggy, 'number': 6, 'route': 2},
			{'time': 5, 'type': Game.enemyType.suicideTruck, 'number': 2, 'route': 1},
			{'time': 5, 'type': Game.enemyType.suicideTruck, 'number': 1, 'route': 2},
			{'time': 5, 'type': Game.enemyType.mediumTank, 'number': 3, 'route': 1},
			{'time': 5, 'type': Game.enemyType.mediumTank, 'number': 3, 'route': 2},
			{'time': 6, 'type': Game.enemyType.missileTruck, 'number': 2, 'route': 1},
			{'time': 6, 'type': Game.enemyType.missileTruck, 'number': 1, 'route': 2},
			{'time': 6, 'type': Game.enemyType.scoutDrone, 'number': 3, 'route': 1},
			{'time': 6, 'type': Game.enemyType.scoutDrone, 'number': 3, 'route': 2},
			{'time': 7, 'type': Game.enemyType.attackHelicopter, 'number': 2, 'route': 1},
			{'time': 7, 'type': Game.enemyType.attackHelicopter, 'number': 1, 'route': 2},
			{'time': 7, 'type': Game.enemyType.heavyTank, 'number': 3, 'route': 1},
			{'time': 7, 'type': Game.enemyType.heavyTank, 'number': 2, 'route': 2},
			{'time': 8, 'type': Game.enemyType.suicideTruck, 'number': 2, 'route': 1},
			{'time': 8, 'type': Game.enemyType.suicideTruck, 'number': 2, 'route': 2},
			{'time': 8, 'type': Game.enemyType.assaultBuggy, 'number': 8, 'route': 1},
			{'time': 8, 'type': Game.enemyType.assaultBuggy, 'number': 8, 'route': 2},
			{'time': 9, 'type': Game.enemyType.missileTruck, 'number': 2, 'route': 1},
			{'time': 9, 'type': Game.enemyType.missileTruck, 'number': 2, 'route': 2},
			{'time': 10, 'type': Game.enemyType.attackHelicopter, 'number': 2, 'route': 1},
			{'time': 10, 'type': Game.enemyType.attackHelicopter, 'number': 2, 'route': 2},
			{'time': 11, 'type': Game.enemyType.heavyTank, 'number': 3, 'route': 1},
			{'time': 11, 'type': Game.enemyType.heavyTank, 'number': 3, 'route': 2},
			{'time': 12, 'type': Game.enemyType.mediumTank, 'number': 4, 'route': 1},
			{'time': 12, 'type': Game.enemyType.mediumTank, 'number': 4, 'route': 2},
			{'time': 13, 'type': Game.enemyType.missileTruck, 'number': 2, 'route': 1},
			{'time': 13, 'type': Game.enemyType.missileTruck, 'number': 2, 'route': 2}
		]
	},
	{
		'name': '11',
		"id": 11,
		'routes': 2,   # 本关路线数（和场景里 Path2D 的数量对应）
		"gemReward": 15,
		'type': '工厂',
		'category': '地下管廊',
		'description': '转入地下管廊，高密度重型单位连续出现',
		'wave': 14,
		'health': 10,
		'money': 500,
		'scene': 'res://scene/level/level_11.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.mediumTank, 'number': 3, 'route': 1},
			{'time': 1, 'type': Game.enemyType.mediumTank, 'number': 2, 'route': 2},
			{'time': 1, 'type': Game.enemyType.assaultBuggy, 'number': 7, 'route': 1},
			{'time': 1, 'type': Game.enemyType.assaultBuggy, 'number': 7, 'route': 2},
			{'time': 2, 'type': Game.enemyType.heavyTank, 'number': 2, 'route': 1},
			{'time': 2, 'type': Game.enemyType.heavyTank, 'number': 2, 'route': 2},
			{'time': 2, 'type': Game.enemyType.scoutDrone, 'number': 3, 'route': 1},
			{'time': 2, 'type': Game.enemyType.scoutDrone, 'number': 3, 'route': 2},
			{'time': 3, 'type': Game.enemyType.missileTruck, 'number': 2, 'route': 1},
			{'time': 3, 'type': Game.enemyType.missileTruck, 'number': 1, 'route': 2},
			{'time': 3, 'type': Game.enemyType.attackHelicopter, 'number': 2, 'route': 1},
			{'time': 3, 'type': Game.enemyType.attackHelicopter, 'number': 1, 'route': 2},
			{'time': 4, 'type': Game.enemyType.suicideTruck, 'number': 2, 'route': 1},
			{'time': 4, 'type': Game.enemyType.suicideTruck, 'number': 2, 'route': 2},
			{'time': 4, 'type': Game.enemyType.mediumTank, 'number': 4, 'route': 1},
			{'time': 4, 'type': Game.enemyType.mediumTank, 'number': 3, 'route': 2},
			{'time': 5, 'type': Game.enemyType.missileTruck, 'number': 2, 'route': 1},
			{'time': 5, 'type': Game.enemyType.missileTruck, 'number': 2, 'route': 2},
			{'time': 5, 'type': Game.enemyType.assaultBuggy, 'number': 8, 'route': 1},
			{'time': 5, 'type': Game.enemyType.assaultBuggy, 'number': 8, 'route': 2},
			{'time': 6, 'type': Game.enemyType.heavyTank, 'number': 3, 'route': 1},
			{'time': 6, 'type': Game.enemyType.heavyTank, 'number': 2, 'route': 2},
			{'time': 6, 'type': Game.enemyType.attackHelicopter, 'number': 2, 'route': 1},
			{'time': 6, 'type': Game.enemyType.attackHelicopter, 'number': 2, 'route': 2},
			{'time': 7, 'type': Game.enemyType.scoutDrone, 'number': 4, 'route': 1},
			{'time': 7, 'type': Game.enemyType.scoutDrone, 'number': 4, 'route': 2},
			{'time': 7, 'type': Game.enemyType.suicideTruck, 'number': 3, 'route': 1},
			{'time': 7, 'type': Game.enemyType.suicideTruck, 'number': 2, 'route': 2},
			{'time': 8, 'type': Game.enemyType.mediumTank, 'number': 4, 'route': 1},
			{'time': 8, 'type': Game.enemyType.mediumTank, 'number': 4, 'route': 2},
			{'time': 8, 'type': Game.enemyType.missileTruck, 'number': 2, 'route': 1},
			{'time': 8, 'type': Game.enemyType.missileTruck, 'number': 2, 'route': 2},
			{'time': 9, 'type': Game.enemyType.heavyTank, 'number': 3, 'route': 1},
			{'time': 9, 'type': Game.enemyType.heavyTank, 'number': 3, 'route': 2},
			{'time': 10, 'type': Game.enemyType.attackHelicopter, 'number': 3, 'route': 1},
			{'time': 10, 'type': Game.enemyType.attackHelicopter, 'number': 2, 'route': 2},
			{'time': 11, 'type': Game.enemyType.suicideTruck, 'number': 3, 'route': 1},
			{'time': 11, 'type': Game.enemyType.suicideTruck, 'number': 3, 'route': 2},
			{'time': 12, 'type': Game.enemyType.missileTruck, 'number': 3, 'route': 1},
			{'time': 12, 'type': Game.enemyType.missileTruck, 'number': 2, 'route': 2},
			{'time': 13, 'type': Game.enemyType.heavyTank, 'number': 4, 'route': 1},
			{'time': 13, 'type': Game.enemyType.heavyTank, 'number': 3, 'route': 2},
			{'time': 14, 'type': Game.enemyType.attackHelicopter, 'number': 3, 'route': 1},
			{'time': 14, 'type': Game.enemyType.attackHelicopter, 'number': 2, 'route': 2}
		]
	},
	{
		'name': '12',
		"id": 12,
		'routes': 2,   # 本关路线数（和场景里 Path2D 的数量对应）
		"gemReward": 16,
		'type': '工厂',
		'category': '动力机房',
		'description': '动力机房内多类型复合波次持续不断',
		'wave': 15,
		'health': 9,
		'money': 550,
		'scene': 'res://scene/level/level_12.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.assaultBuggy, 'number': 8, 'route': 1},
			{'time': 1, 'type': Game.enemyType.assaultBuggy, 'number': 8, 'route': 2},
			{'time': 1, 'type': Game.enemyType.scoutDrone, 'number': 3, 'route': 1},
			{'time': 1, 'type': Game.enemyType.scoutDrone, 'number': 3, 'route': 2},
			{'time': 2, 'type': Game.enemyType.mediumTank, 'number': 3, 'route': 1},
			{'time': 2, 'type': Game.enemyType.mediumTank, 'number': 3, 'route': 2},
			{'time': 2, 'type': Game.enemyType.heavyTank, 'number': 2, 'route': 1},
			{'time': 2, 'type': Game.enemyType.heavyTank, 'number': 1, 'route': 2},
			{'time': 3, 'type': Game.enemyType.missileTruck, 'number': 2, 'route': 1},
			{'time': 3, 'type': Game.enemyType.missileTruck, 'number': 2, 'route': 2},
			{'time': 3, 'type': Game.enemyType.attackHelicopter, 'number': 2, 'route': 1},
			{'time': 3, 'type': Game.enemyType.attackHelicopter, 'number': 1, 'route': 2},
			{'time': 4, 'type': Game.enemyType.suicideTruck, 'number': 3, 'route': 1},
			{'time': 4, 'type': Game.enemyType.suicideTruck, 'number': 2, 'route': 2},
			{'time': 4, 'type': Game.enemyType.assaultBuggy, 'number': 9, 'route': 1},
			{'time': 4, 'type': Game.enemyType.assaultBuggy, 'number': 9, 'route': 2},
			{'time': 5, 'type': Game.enemyType.heavyTank, 'number': 3, 'route': 1},
			{'time': 5, 'type': Game.enemyType.heavyTank, 'number': 3, 'route': 2},
			{'time': 5, 'type': Game.enemyType.mediumTank, 'number': 4, 'route': 1},
			{'time': 5, 'type': Game.enemyType.mediumTank, 'number': 4, 'route': 2},
			{'time': 6, 'type': Game.enemyType.missileTruck, 'number': 3, 'route': 1},
			{'time': 6, 'type': Game.enemyType.missileTruck, 'number': 2, 'route': 2},
			{'time': 6, 'type': Game.enemyType.scoutDrone, 'number': 4, 'route': 1},
			{'time': 6, 'type': Game.enemyType.scoutDrone, 'number': 4, 'route': 2},
			{'time': 7, 'type': Game.enemyType.attackHelicopter, 'number': 2, 'route': 1},
			{'time': 7, 'type': Game.enemyType.attackHelicopter, 'number': 2, 'route': 2},
			{'time': 7, 'type': Game.enemyType.suicideTruck, 'number': 3, 'route': 1},
			{'time': 7, 'type': Game.enemyType.suicideTruck, 'number': 3, 'route': 2},
			{'time': 8, 'type': Game.enemyType.heavyTank, 'number': 4, 'route': 1},
			{'time': 8, 'type': Game.enemyType.heavyTank, 'number': 3, 'route': 2},
			{'time': 8, 'type': Game.enemyType.assaultBuggy, 'number': 10, 'route': 1},
			{'time': 8, 'type': Game.enemyType.assaultBuggy, 'number': 10, 'route': 2},
			{'time': 9, 'type': Game.enemyType.missileTruck, 'number': 3, 'route': 1},
			{'time': 9, 'type': Game.enemyType.missileTruck, 'number': 2, 'route': 2},
			{'time': 10, 'type': Game.enemyType.attackHelicopter, 'number': 3, 'route': 1},
			{'time': 10, 'type': Game.enemyType.attackHelicopter, 'number': 2, 'route': 2},
			{'time': 11, 'type': Game.enemyType.mediumTank, 'number': 5, 'route': 1},
			{'time': 11, 'type': Game.enemyType.mediumTank, 'number': 5, 'route': 2},
			{'time': 12, 'type': Game.enemyType.suicideTruck, 'number': 4, 'route': 1},
			{'time': 12, 'type': Game.enemyType.suicideTruck, 'number': 3, 'route': 2},
			{'time': 13, 'type': Game.enemyType.heavyTank, 'number': 4, 'route': 1},
			{'time': 13, 'type': Game.enemyType.heavyTank, 'number': 4, 'route': 2},
			{'time': 14, 'type': Game.enemyType.missileTruck, 'number': 3, 'route': 1},
			{'time': 14, 'type': Game.enemyType.missileTruck, 'number': 3, 'route': 2},
			{'time': 15, 'type': Game.enemyType.attackHelicopter, 'number': 3, 'route': 1},
			{'time': 15, 'type': Game.enemyType.attackHelicopter, 'number': 3, 'route': 2}
		]
	},
	{
		'name': '13',
		"id": 13,
		'routes': 2,   # 本关路线数（和场景里 Path2D 的数量对应）
		"gemReward": 17,
		'type': '工厂',
		'category': '自动化仓储',
		'description': '自动化仓储，远程火力与重型单位同步增强',
		'wave': 16,
		'health': 9,
		'money': 600,
		'scene': 'res://scene/level/level_13.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.mediumTank, 'number': 4, 'route': 1},
			{'time': 1, 'type': Game.enemyType.mediumTank, 'number': 3, 'route': 2},
			{'time': 1, 'type': Game.enemyType.assaultBuggy, 'number': 9, 'route': 1},
			{'time': 1, 'type': Game.enemyType.assaultBuggy, 'number': 9, 'route': 2},
			{'time': 2, 'type': Game.enemyType.missileTruck, 'number': 2, 'route': 1},
			{'time': 2, 'type': Game.enemyType.missileTruck, 'number': 2, 'route': 2},
			{'time': 2, 'type': Game.enemyType.scoutDrone, 'number': 4, 'route': 1},
			{'time': 2, 'type': Game.enemyType.scoutDrone, 'number': 4, 'route': 2},
			{'time': 3, 'type': Game.enemyType.heavyTank, 'number': 3, 'route': 1},
			{'time': 3, 'type': Game.enemyType.heavyTank, 'number': 2, 'route': 2},
			{'time': 3, 'type': Game.enemyType.attackHelicopter, 'number': 2, 'route': 1},
			{'time': 3, 'type': Game.enemyType.attackHelicopter, 'number': 2, 'route': 2},
			{'time': 4, 'type': Game.enemyType.suicideTruck, 'number': 3, 'route': 1},
			{'time': 4, 'type': Game.enemyType.suicideTruck, 'number': 3, 'route': 2},
			{'time': 4, 'type': Game.enemyType.mediumTank, 'number': 5, 'route': 1},
			{'time': 4, 'type': Game.enemyType.mediumTank, 'number': 4, 'route': 2},
			{'time': 5, 'type': Game.enemyType.missileTruck, 'number': 3, 'route': 1},
			{'time': 5, 'type': Game.enemyType.missileTruck, 'number': 2, 'route': 2},
			{'time': 5, 'type': Game.enemyType.assaultBuggy, 'number': 10, 'route': 1},
			{'time': 5, 'type': Game.enemyType.assaultBuggy, 'number': 10, 'route': 2},
			{'time': 6, 'type': Game.enemyType.heavyTank, 'number': 4, 'route': 1},
			{'time': 6, 'type': Game.enemyType.heavyTank, 'number': 3, 'route': 2},
			{'time': 6, 'type': Game.enemyType.scoutDrone, 'number': 5, 'route': 1},
			{'time': 6, 'type': Game.enemyType.scoutDrone, 'number': 5, 'route': 2},
			{'time': 7, 'type': Game.enemyType.attackHelicopter, 'number': 3, 'route': 1},
			{'time': 7, 'type': Game.enemyType.attackHelicopter, 'number': 2, 'route': 2},
			{'time': 7, 'type': Game.enemyType.suicideTruck, 'number': 4, 'route': 1},
			{'time': 7, 'type': Game.enemyType.suicideTruck, 'number': 3, 'route': 2},
			{'time': 8, 'type': Game.enemyType.missileTruck, 'number': 3, 'route': 1},
			{'time': 8, 'type': Game.enemyType.missileTruck, 'number': 3, 'route': 2},
			{'time': 8, 'type': Game.enemyType.mediumTank, 'number': 5, 'route': 1},
			{'time': 8, 'type': Game.enemyType.mediumTank, 'number': 5, 'route': 2},
			{'time': 9, 'type': Game.enemyType.heavyTank, 'number': 4, 'route': 1},
			{'time': 9, 'type': Game.enemyType.heavyTank, 'number': 4, 'route': 2},
			{'time': 10, 'type': Game.enemyType.attackHelicopter, 'number': 3, 'route': 1},
			{'time': 10, 'type': Game.enemyType.attackHelicopter, 'number': 3, 'route': 2},
			{'time': 11, 'type': Game.enemyType.suicideTruck, 'number': 4, 'route': 1},
			{'time': 11, 'type': Game.enemyType.suicideTruck, 'number': 4, 'route': 2},
			{'time': 12, 'type': Game.enemyType.missileTruck, 'number': 4, 'route': 1},
			{'time': 12, 'type': Game.enemyType.missileTruck, 'number': 3, 'route': 2},
			{'time': 13, 'type': Game.enemyType.heavyTank, 'number': 5, 'route': 1},
			{'time': 13, 'type': Game.enemyType.heavyTank, 'number': 4, 'route': 2},
			{'time': 14, 'type': Game.enemyType.attackHelicopter, 'number': 4, 'route': 1},
			{'time': 14, 'type': Game.enemyType.attackHelicopter, 'number': 3, 'route': 2},
			{'time': 15, 'type': Game.enemyType.mediumTank, 'number': 6, 'route': 1},
			{'time': 15, 'type': Game.enemyType.mediumTank, 'number': 6, 'route': 2},
			{'time': 16, 'type': Game.enemyType.missileTruck, 'number': 4, 'route': 1},
			{'time': 16, 'type': Game.enemyType.missileTruck, 'number': 4, 'route': 2}
		]
	},
	{
		'name': '14',
		"id": 14,
		'routes': 2,   # 本关路线数（和场景里 Path2D 的数量对应）
		"gemReward": 18,
		'type': '工厂',
		'category': '核心装配线',
		'description': '核心装配线，高数量、高强度的综合防守',
		'wave': 17,
		'health': 8,
		'money': 650,
		'scene': 'res://scene/level/level_14.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.assaultBuggy, 'number': 10, 'route': 1},
			{'time': 1, 'type': Game.enemyType.assaultBuggy, 'number': 10, 'route': 2},
			{'time': 1, 'type': Game.enemyType.scoutDrone, 'number': 4, 'route': 1},
			{'time': 1, 'type': Game.enemyType.scoutDrone, 'number': 4, 'route': 2},
			{'time': 2, 'type': Game.enemyType.heavyTank, 'number': 3, 'route': 1},
			{'time': 2, 'type': Game.enemyType.heavyTank, 'number': 3, 'route': 2},
			{'time': 2, 'type': Game.enemyType.mediumTank, 'number': 4, 'route': 1},
			{'time': 2, 'type': Game.enemyType.mediumTank, 'number': 4, 'route': 2},
			{'time': 3, 'type': Game.enemyType.missileTruck, 'number': 3, 'route': 1},
			{'time': 3, 'type': Game.enemyType.missileTruck, 'number': 2, 'route': 2},
			{'time': 3, 'type': Game.enemyType.attackHelicopter, 'number': 3, 'route': 1},
			{'time': 3, 'type': Game.enemyType.attackHelicopter, 'number': 2, 'route': 2},
			{'time': 4, 'type': Game.enemyType.suicideTruck, 'number': 4, 'route': 1},
			{'time': 4, 'type': Game.enemyType.suicideTruck, 'number': 3, 'route': 2},
			{'time': 4, 'type': Game.enemyType.assaultBuggy, 'number': 11, 'route': 1},
			{'time': 4, 'type': Game.enemyType.assaultBuggy, 'number': 11, 'route': 2},
			{'time': 5, 'type': Game.enemyType.missileTruck, 'number': 3, 'route': 1},
			{'time': 5, 'type': Game.enemyType.missileTruck, 'number': 3, 'route': 2},
			{'time': 5, 'type': Game.enemyType.heavyTank, 'number': 4, 'route': 1},
			{'time': 5, 'type': Game.enemyType.heavyTank, 'number': 4, 'route': 2},
			{'time': 6, 'type': Game.enemyType.scoutDrone, 'number': 6, 'route': 1},
			{'time': 6, 'type': Game.enemyType.scoutDrone, 'number': 6, 'route': 2},
			{'time': 6, 'type': Game.enemyType.attackHelicopter, 'number': 3, 'route': 1},
			{'time': 6, 'type': Game.enemyType.attackHelicopter, 'number': 3, 'route': 2},
			{'time': 7, 'type': Game.enemyType.mediumTank, 'number': 6, 'route': 1},
			{'time': 7, 'type': Game.enemyType.mediumTank, 'number': 6, 'route': 2},
			{'time': 7, 'type': Game.enemyType.suicideTruck, 'number': 4, 'route': 1},
			{'time': 7, 'type': Game.enemyType.suicideTruck, 'number': 4, 'route': 2},
			{'time': 8, 'type': Game.enemyType.missileTruck, 'number': 4, 'route': 1},
			{'time': 8, 'type': Game.enemyType.missileTruck, 'number': 3, 'route': 2},
			{'time': 8, 'type': Game.enemyType.heavyTank, 'number': 5, 'route': 1},
			{'time': 8, 'type': Game.enemyType.heavyTank, 'number': 4, 'route': 2},
			{'time': 9, 'type': Game.enemyType.attackHelicopter, 'number': 4, 'route': 1},
			{'time': 9, 'type': Game.enemyType.attackHelicopter, 'number': 3, 'route': 2},
			{'time': 10, 'type': Game.enemyType.assaultBuggy, 'number': 12, 'route': 1},
			{'time': 10, 'type': Game.enemyType.assaultBuggy, 'number': 12, 'route': 2},
			{'time': 11, 'type': Game.enemyType.suicideTruck, 'number': 5, 'route': 1},
			{'time': 11, 'type': Game.enemyType.suicideTruck, 'number': 4, 'route': 2},
			{'time': 12, 'type': Game.enemyType.missileTruck, 'number': 4, 'route': 1},
			{'time': 12, 'type': Game.enemyType.missileTruck, 'number': 4, 'route': 2},
			{'time': 13, 'type': Game.enemyType.heavyTank, 'number': 5, 'route': 1},
			{'time': 13, 'type': Game.enemyType.heavyTank, 'number': 5, 'route': 2},
			{'time': 14, 'type': Game.enemyType.attackHelicopter, 'number': 4, 'route': 1},
			{'time': 14, 'type': Game.enemyType.attackHelicopter, 'number': 4, 'route': 2},
			{'time': 15, 'type': Game.enemyType.mediumTank, 'number': 7, 'route': 1},
			{'time': 15, 'type': Game.enemyType.mediumTank, 'number': 7, 'route': 2},
			{'time': 16, 'type': Game.enemyType.missileTruck, 'number': 5, 'route': 1},
			{'time': 16, 'type': Game.enemyType.missileTruck, 'number': 4, 'route': 2},
			{'time': 17, 'type': Game.enemyType.heavyTank, 'number': 6, 'route': 1},
			{'time': 17, 'type': Game.enemyType.heavyTank, 'number': 5, 'route': 2}
		]
	},
	{
		'name': '15',
		"id": 15,
		'routes': 2,   # 本关路线数（和场景里 Path2D 的数量对应）
		"gemReward": 20,
		'type': '工厂',
		'category': '工厂核心',
		'description': '工厂核心，最终关卡，迎接最大规模的敌群',
		'wave': 18,
		'health': 8,
		'money': 720,
		'scene': 'res://scene/level/level_15.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.mediumTank, 'number': 5, 'route': 1},
			{'time': 1, 'type': Game.enemyType.mediumTank, 'number': 4, 'route': 2},
			{'time': 1, 'type': Game.enemyType.assaultBuggy, 'number': 11, 'route': 1},
			{'time': 1, 'type': Game.enemyType.assaultBuggy, 'number': 11, 'route': 2},
			{'time': 2, 'type': Game.enemyType.missileTruck, 'number': 3, 'route': 1},
			{'time': 2, 'type': Game.enemyType.missileTruck, 'number': 3, 'route': 2},
			{'time': 2, 'type': Game.enemyType.scoutDrone, 'number': 5, 'route': 1},
			{'time': 2, 'type': Game.enemyType.scoutDrone, 'number': 5, 'route': 2},
			{'time': 3, 'type': Game.enemyType.heavyTank, 'number': 4, 'route': 1},
			{'time': 3, 'type': Game.enemyType.heavyTank, 'number': 3, 'route': 2},
			{'time': 3, 'type': Game.enemyType.attackHelicopter, 'number': 3, 'route': 1},
			{'time': 3, 'type': Game.enemyType.attackHelicopter, 'number': 3, 'route': 2},
			{'time': 4, 'type': Game.enemyType.suicideTruck, 'number': 4, 'route': 1},
			{'time': 4, 'type': Game.enemyType.suicideTruck, 'number': 4, 'route': 2},
			{'time': 4, 'type': Game.enemyType.assaultBuggy, 'number': 12, 'route': 1},
			{'time': 4, 'type': Game.enemyType.assaultBuggy, 'number': 12, 'route': 2},
			{'time': 5, 'type': Game.enemyType.missileTruck, 'number': 4, 'route': 1},
			{'time': 5, 'type': Game.enemyType.missileTruck, 'number': 3, 'route': 2},
			{'time': 5, 'type': Game.enemyType.mediumTank, 'number': 6, 'route': 1},
			{'time': 5, 'type': Game.enemyType.mediumTank, 'number': 6, 'route': 2},
			{'time': 6, 'type': Game.enemyType.heavyTank, 'number': 5, 'route': 1},
			{'time': 6, 'type': Game.enemyType.heavyTank, 'number': 4, 'route': 2},
			{'time': 6, 'type': Game.enemyType.scoutDrone, 'number': 7, 'route': 1},
			{'time': 6, 'type': Game.enemyType.scoutDrone, 'number': 7, 'route': 2},
			{'time': 7, 'type': Game.enemyType.attackHelicopter, 'number': 4, 'route': 1},
			{'time': 7, 'type': Game.enemyType.attackHelicopter, 'number': 3, 'route': 2},
			{'time': 7, 'type': Game.enemyType.suicideTruck, 'number': 5, 'route': 1},
			{'time': 7, 'type': Game.enemyType.suicideTruck, 'number': 4, 'route': 2},
			{'time': 8, 'type': Game.enemyType.missileTruck, 'number': 4, 'route': 1},
			{'time': 8, 'type': Game.enemyType.missileTruck, 'number': 4, 'route': 2},
			{'time': 8, 'type': Game.enemyType.heavyTank, 'number': 5, 'route': 1},
			{'time': 8, 'type': Game.enemyType.heavyTank, 'number': 5, 'route': 2},
			{'time': 9, 'type': Game.enemyType.attackHelicopter, 'number': 4, 'route': 1},
			{'time': 9, 'type': Game.enemyType.attackHelicopter, 'number': 4, 'route': 2},
			{'time': 10, 'type': Game.enemyType.assaultBuggy, 'number': 13, 'route': 1},
			{'time': 10, 'type': Game.enemyType.assaultBuggy, 'number': 13, 'route': 2},
			{'time': 11, 'type': Game.enemyType.suicideTruck, 'number': 5, 'route': 1},
			{'time': 11, 'type': Game.enemyType.suicideTruck, 'number': 5, 'route': 2},
			{'time': 12, 'type': Game.enemyType.missileTruck, 'number': 5, 'route': 1},
			{'time': 12, 'type': Game.enemyType.missileTruck, 'number': 4, 'route': 2},
			{'time': 13, 'type': Game.enemyType.heavyTank, 'number': 6, 'route': 1},
			{'time': 13, 'type': Game.enemyType.heavyTank, 'number': 6, 'route': 2},
			{'time': 14, 'type': Game.enemyType.attackHelicopter, 'number': 5, 'route': 1},
			{'time': 14, 'type': Game.enemyType.attackHelicopter, 'number': 4, 'route': 2},
			{'time': 15, 'type': Game.enemyType.mediumTank, 'number': 8, 'route': 1},
			{'time': 15, 'type': Game.enemyType.mediumTank, 'number': 8, 'route': 2},
			{'time': 16, 'type': Game.enemyType.missileTruck, 'number': 5, 'route': 1},
			{'time': 16, 'type': Game.enemyType.missileTruck, 'number': 5, 'route': 2},
			{'time': 17, 'type': Game.enemyType.suicideTruck, 'number': 6, 'route': 1},
			{'time': 17, 'type': Game.enemyType.suicideTruck, 'number': 6, 'route': 2},
			{'time': 18, 'type': Game.enemyType.heavyTank, 'number': 7, 'route': 1},
			{'time': 18, 'type': Game.enemyType.heavyTank, 'number': 7, 'route': 2}
		]
	},
]

var enemyScenes = {
	Game.enemyType.miniTank: preload("res://scene/enemy/miniTank.tscn"),
	Game.enemyType.mediumTank: preload("res://scene/enemy/medium_tank.tscn"),
	Game.enemyType.heavyTank: preload("res://scene/enemy/heavy_tank.tscn"),
	Game.enemyType.armoredTank: preload("res://scene/enemy/armored_tank.tscn"),
	Game.enemyType.assaultBuggy: preload("res://scene/enemy/assault_buggy.tscn"),
	Game.enemyType.medic: preload("res://scene/enemy/medic.tscn"),
	Game.enemyType.suicideTruck: preload("res://scene/enemy/suicide_truck.tscn"),
	Game.enemyType.missileTruck: preload("res://scene/enemy/missile_truck.tscn"),
	Game.enemyType.scoutDrone: preload("res://scene/enemy/scout_drone.tscn"),
	Game.enemyType.attackHelicopter: preload("res://scene/enemy/attack_helicopter.tscn")
}
