extends Node

const TileSize = 64  #网格大小

# 当前选中的关卡ID（由 level_select 点击时设置，map 读取后加载对应场景）
var currentStageId: int = 1

#关卡的数据
var allStage = [
	{
		'name': 'Tutorial',
		"id": 0,
		'selectable': false,
		'type': '教程',
		'category': '新手教程',
		'description': '基础教学关卡，沿着一条简单直线展开，逐一了解各类敌人的威胁与节奏',
		'wave': 10,
		'health': 25,
		'money': 1200,
		'scene': 'res://scene/level/level_tutorial.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.miniTank, 'number': 1},
			{'time': 2, 'type': Game.enemyType.mediumTank, 'number': 1},
			{'time': 3, 'type': Game.enemyType.heavyTank, 'number': 1},
			{'time': 4, 'type': Game.enemyType.armoredTank, 'number': 1},
			{'time': 5, 'type': Game.enemyType.assaultBuggy, 'number': 1},
			{'time': 6, 'type': Game.enemyType.medic, 'number': 1},
			{'time': 7, 'type': Game.enemyType.suicideTruck, 'number': 1},
			{'time': 8, 'type': Game.enemyType.missileTruck, 'number': 1},
			{'time': 9, 'type': Game.enemyType.scoutDrone, 'number': 1},
			{'time': 10, 'type': Game.enemyType.attackHelicopter, 'number': 1}
		]
	},
	{
		'name': '1',
		"id": 1,
		'type': '草地',
		'category': '草地训练场',
		'description': '第一片草地训练场，路线开阔，适合熟悉防守节奏',
		'wave': 3,
		'health': 20,
		'money': 150,
		'scene': 'res://scene/level/level_1.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.miniTank, 'number': 2},
			{'time': 2, 'type': Game.enemyType.miniTank, 'number': 3},
			{'time': 3, 'type': Game.enemyType.miniTank, 'number': 4}
		]
	},
	{
		'name': '2',
		"id": 2,
		'type': '草地',
		'category': '草地边缘',
		'description': '草地边缘道路较为开阔，适合练习分流与机枪覆盖',
		'wave': 5,
		'health': 18,
		'money': 200,
		'scene': 'res://scene/level/level_2.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.miniTank, 'number': 3},
			{'time': 2, 'type': Game.enemyType.miniTank, 'number': 4},
			{'time': 2, 'type': Game.enemyType.assaultBuggy, 'number': 2},
			{'time': 3, 'type': Game.enemyType.miniTank, 'number': 5},
			{'time': 3, 'type': Game.enemyType.assaultBuggy, 'number': 2},
			{'time': 4, 'type': Game.enemyType.miniTank, 'number': 6},
			{'time': 4, 'type': Game.enemyType.assaultBuggy, 'number': 3},
			{'time': 5, 'type': Game.enemyType.mediumTank, 'number': 1},
			{'time': 5, 'type': Game.enemyType.assaultBuggy, 'number': 4}
		]
	},
	{
		'name': '3',
		"id": 3,
		'type': '草地',
		'category': '草地入口',
		'description': '草地入口道路变窄，开始引入重型目标和压制路线',
		'wave': 5,
		'health': 18,
		'money': 220,
		'scene': 'res://scene/level/level_3.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.miniTank, 'number': 4},
			{'time': 2, 'type': Game.enemyType.miniTank, 'number': 5},
			{'time': 2, 'type': Game.enemyType.mediumTank, 'number': 1},
			{'time': 3, 'type': Game.enemyType.miniTank, 'number': 6},
			{'time': 3, 'type': Game.enemyType.mediumTank, 'number': 1},
			{'time': 4, 'type': Game.enemyType.assaultBuggy, 'number': 3},
			{'time': 4, 'type': Game.enemyType.mediumTank, 'number': 2},
			{'time': 5, 'type': Game.enemyType.heavyTank, 'number': 1}
		]
	},
	{
		'name': '4',
		"id": 4,
		'type': '工厂',
		'category': '工厂入口',
		'description': '工厂入口道路转角增多，适合分流与自爆威胁处理',
		'wave': 7,
		'health': 16,
		'money': 190,
		'scene': 'res://scene/level/level_4.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.assaultBuggy, 'number': 5},
			{'time': 1, 'type': Game.enemyType.miniTank, 'number': 4},
			{'time': 2, 'type': Game.enemyType.assaultBuggy, 'number': 7},
			{'time': 2, 'type': Game.enemyType.mediumTank, 'number': 1},
			{'time': 3, 'type': Game.enemyType.miniTank, 'number': 10},
			{'time': 3, 'type': Game.enemyType.mediumTank, 'number': 2},
			{'time': 4, 'type': Game.enemyType.suicideTruck, 'number': 1},
			{'time': 4, 'type': Game.enemyType.assaultBuggy, 'number': 8},
			{'time': 5, 'type': Game.enemyType.heavyTank, 'number': 2},
			{'time': 5, 'type': Game.enemyType.assaultBuggy, 'number': 6},
			{'time': 6, 'type': Game.enemyType.suicideTruck, 'number': 2},
			{'time': 6, 'type': Game.enemyType.mediumTank, 'number': 3},
			{'time': 7, 'type': Game.enemyType.heavyTank, 'number': 2},
			{'time': 7, 'type': Game.enemyType.assaultBuggy, 'number': 10}
		]
	},
	{
		'name': '5',
		"id": 5,
		'type': '工厂',
		'category': '工厂中段',
		'description': '工厂中段夹道更长，导弹车和重型单位威胁开始出现',
		'wave': 8,
		'health': 14,
		'money': 230,
		'scene': 'res://scene/level/level_5.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.miniTank, 'number': 6},
			{'time': 1, 'type': Game.enemyType.mediumTank, 'number': 1},
			{'time': 2, 'type': Game.enemyType.missileTruck, 'number': 1},
			{'time': 2, 'type': Game.enemyType.assaultBuggy, 'number': 5},
			{'time': 3, 'type': Game.enemyType.mediumTank, 'number': 3},
			{'time': 3, 'type': Game.enemyType.miniTank, 'number': 8},
			{'time': 4, 'type': Game.enemyType.missileTruck, 'number': 1},
			{'time': 4, 'type': Game.enemyType.heavyTank, 'number': 1},
			{'time': 5, 'type': Game.enemyType.mediumTank, 'number': 4},
			{'time': 5, 'type': Game.enemyType.assaultBuggy, 'number': 8},
			{'time': 6, 'type': Game.enemyType.missileTruck, 'number': 2},
			{'time': 6, 'type': Game.enemyType.heavyTank, 'number': 2},
			{'time': 7, 'type': Game.enemyType.suicideTruck, 'number': 2},
			{'time': 7, 'type': Game.enemyType.mediumTank, 'number': 5},
			{'time': 8, 'type': Game.enemyType.missileTruck, 'number': 2},
			{'time': 8, 'type': Game.enemyType.heavyTank, 'number': 3}
		]
	},
	{
		'name': '6',
		"id": 6,
		'type': '工厂',
		'category': '工厂后场',
		'description': '工厂后场通道更长，首次出现空地混合攻击',
		'wave': 9,
		'health': 12,
		'money': 280,
		'scene': 'res://scene/level/level_6.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.assaultBuggy, 'number': 6},
			{'time': 1, 'type': Game.enemyType.scoutDrone, 'number': 2},
			{'time': 2, 'type': Game.enemyType.miniTank, 'number': 8},
			{'time': 2, 'type': Game.enemyType.mediumTank, 'number': 2},
			{'time': 3, 'type': Game.enemyType.attackHelicopter, 'number': 1},
			{'time': 3, 'type': Game.enemyType.assaultBuggy, 'number': 8},
			{'time': 4, 'type': Game.enemyType.missileTruck, 'number': 1},
			{'time': 4, 'type': Game.enemyType.heavyTank, 'number': 2},
			{'time': 5, 'type': Game.enemyType.attackHelicopter, 'number': 2},
			{'time': 5, 'type': Game.enemyType.mediumTank, 'number': 4},
			{'time': 6, 'type': Game.enemyType.suicideTruck, 'number': 2},
			{'time': 6, 'type': Game.enemyType.scoutDrone, 'number': 4},
			{'time': 7, 'type': Game.enemyType.missileTruck, 'number': 2},
			{'time': 7, 'type': Game.enemyType.heavyTank, 'number': 3},
			{'time': 8, 'type': Game.enemyType.attackHelicopter, 'number': 2},
			{'time': 8, 'type': Game.enemyType.mediumTank, 'number': 5},
			{'time': 9, 'type': Game.enemyType.missileTruck, 'number': 3},
			{'time': 9, 'type': Game.enemyType.heavyTank, 'number': 4}
		]
	},
	{
		'name': '7',
		"id": 7,
		'type': '沙漠',
		'category': '沙漠前线',
		'description': '沙漠前线道路更长，敌人密度开始明显提升',
		'wave': 10,
		'health': 12,
		'money': 320,
		'scene': 'res://scene/level/level_7.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.miniTank, 'number': 8},
			{'time': 1, 'type': Game.enemyType.scoutDrone, 'number': 2},
			{'time': 2, 'type': Game.enemyType.assaultBuggy, 'number': 8},
			{'time': 2, 'type': Game.enemyType.mediumTank, 'number': 3},
			{'time': 3, 'type': Game.enemyType.attackHelicopter, 'number': 1},
			{'time': 3, 'type': Game.enemyType.miniTank, 'number': 10},
			{'time': 4, 'type': Game.enemyType.missileTruck, 'number': 1},
			{'time': 4, 'type': Game.enemyType.assaultBuggy, 'number': 10},
			{'time': 5, 'type': Game.enemyType.heavyTank, 'number': 2},
			{'time': 5, 'type': Game.enemyType.mediumTank, 'number': 4},
			{'time': 6, 'type': Game.enemyType.attackHelicopter, 'number': 2},
			{'time': 6, 'type': Game.enemyType.scoutDrone, 'number': 4},
			{'time': 7, 'type': Game.enemyType.suicideTruck, 'number': 2},
			{'time': 7, 'type': Game.enemyType.missileTruck, 'number': 2},
			{'time': 8, 'type': Game.enemyType.heavyTank, 'number': 3},
			{'time': 8, 'type': Game.enemyType.assaultBuggy, 'number': 12},
			{'time': 9, 'type': Game.enemyType.attackHelicopter, 'number': 2},
			{'time': 10, 'type': Game.enemyType.missileTruck, 'number': 3}
		]
	},
	{
		'name': '8',
		"id": 8,
		'type': '沙漠',
		'category': '沙漠据点',
		'description': '沙漠据点道路更窄，空中和远程单位密度显著提高',
		'wave': 11,
		'health': 11,
		'money': 360,
		'scene': 'res://scene/level/level_8.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.assaultBuggy, 'number': 10},
			{'time': 1, 'type': Game.enemyType.mediumTank, 'number': 2},
			{'time': 2, 'type': Game.enemyType.scoutDrone, 'number': 4},
			{'time': 2, 'type': Game.enemyType.miniTank, 'number': 10},
			{'time': 3, 'type': Game.enemyType.heavyTank, 'number': 2},
			{'time': 3, 'type': Game.enemyType.assaultBuggy, 'number': 8},
			{'time': 4, 'type': Game.enemyType.missileTruck, 'number': 2},
			{'time': 4, 'type': Game.enemyType.mediumTank, 'number': 4},
			{'time': 5, 'type': Game.enemyType.attackHelicopter, 'number': 2},
			{'time': 5, 'type': Game.enemyType.scoutDrone, 'number': 5},
			{'time': 6, 'type': Game.enemyType.suicideTruck, 'number': 2},
			{'time': 6, 'type': Game.enemyType.heavyTank, 'number': 3},
			{'time': 7, 'type': Game.enemyType.missileTruck, 'number': 2},
			{'time': 7, 'type': Game.enemyType.attackHelicopter, 'number': 3},
			{'time': 8, 'type': Game.enemyType.mediumTank, 'number': 5},
			{'time': 8, 'type': Game.enemyType.assaultBuggy, 'number': 12},
			{'time': 9, 'type': Game.enemyType.heavyTank, 'number': 4},
			{'time': 10, 'type': Game.enemyType.suicideTruck, 'number': 3},
			{'time': 11, 'type': Game.enemyType.missileTruck, 'number': 3}
		]
	},
	{
		'name': '9',
		"id": 9,
		'type': '沙漠',
		'category': '沙漠末端',
		'description': '沙漠末端高数量敌群压境，防线需要持续压制',
		'wave': 12,
		'health': 11,
		'money': 400,
		'scene': 'res://scene/level/level_9.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.miniTank, 'number': 12},
			{'time': 1, 'type': Game.enemyType.mediumTank, 'number': 3},
			{'time': 2, 'type': Game.enemyType.missileTruck, 'number': 2},
			{'time': 2, 'type': Game.enemyType.assaultBuggy, 'number': 10},
			{'time': 3, 'type': Game.enemyType.heavyTank, 'number': 3},
			{'time': 3, 'type': Game.enemyType.scoutDrone, 'number': 5},
			{'time': 4, 'type': Game.enemyType.attackHelicopter, 'number': 2},
			{'time': 4, 'type': Game.enemyType.mediumTank, 'number': 5},
			{'time': 5, 'type': Game.enemyType.suicideTruck, 'number': 3},
			{'time': 5, 'type': Game.enemyType.assaultBuggy, 'number': 12},
			{'time': 6, 'type': Game.enemyType.missileTruck, 'number': 3},
			{'time': 6, 'type': Game.enemyType.heavyTank, 'number': 4},
			{'time': 7, 'type': Game.enemyType.attackHelicopter, 'number': 3},
			{'time': 7, 'type': Game.enemyType.scoutDrone, 'number': 6},
			{'time': 8, 'type': Game.enemyType.mediumTank, 'number': 6},
			{'time': 8, 'type': Game.enemyType.assaultBuggy, 'number': 14},
			{'time': 9, 'type': Game.enemyType.suicideTruck, 'number': 4},
			{'time': 10, 'type': Game.enemyType.missileTruck, 'number': 3},
			{'time': 11, 'type': Game.enemyType.heavyTank, 'number': 5},
			{'time': 12, 'type': Game.enemyType.attackHelicopter, 'number': 4}
		]
	},
	{
		'name': '10',
		"id": 10,
		'type': '沙漠',
		'category': '沙漠决战',
		'description': '沙漠决战综合考验地面、空中和远程防守',
		'wave': 13,
		'health': 10,
		'money': 450,
		'scene': 'res://scene/level/level_10.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.assaultBuggy, 'number': 12},
			{'time': 1, 'type': Game.enemyType.scoutDrone, 'number': 4},
			{'time': 2, 'type': Game.enemyType.mediumTank, 'number': 4},
			{'time': 2, 'type': Game.enemyType.miniTank, 'number': 12},
			{'time': 3, 'type': Game.enemyType.missileTruck, 'number': 2},
			{'time': 3, 'type': Game.enemyType.attackHelicopter, 'number': 2},
			{'time': 4, 'type': Game.enemyType.heavyTank, 'number': 4},
			{'time': 4, 'type': Game.enemyType.assaultBuggy, 'number': 12},
			{'time': 5, 'type': Game.enemyType.suicideTruck, 'number': 3},
			{'time': 5, 'type': Game.enemyType.mediumTank, 'number': 6},
			{'time': 6, 'type': Game.enemyType.missileTruck, 'number': 3},
			{'time': 6, 'type': Game.enemyType.scoutDrone, 'number': 6},
			{'time': 7, 'type': Game.enemyType.attackHelicopter, 'number': 3},
			{'time': 7, 'type': Game.enemyType.heavyTank, 'number': 5},
			{'time': 8, 'type': Game.enemyType.suicideTruck, 'number': 4},
			{'time': 8, 'type': Game.enemyType.assaultBuggy, 'number': 16},
			{'time': 9, 'type': Game.enemyType.missileTruck, 'number': 4},
			{'time': 10, 'type': Game.enemyType.attackHelicopter, 'number': 4},
			{'time': 11, 'type': Game.enemyType.heavyTank, 'number': 6},
			{'time': 12, 'type': Game.enemyType.mediumTank, 'number': 8},
			{'time': 13, 'type': Game.enemyType.missileTruck, 'number': 4}
		]
	},
	{
		'name': '11',
		"id": 11,
		'category': '高压挑战',
		'description': '高密度重型单位开始连续出现',
		'wave': 14,
		'health': 10,
		'money': 500,
		'scene': 'res://scene/level/level_1.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.mediumTank, 'number': 5},
			{'time': 1, 'type': Game.enemyType.assaultBuggy, 'number': 14},
			{'time': 2, 'type': Game.enemyType.heavyTank, 'number': 4},
			{'time': 2, 'type': Game.enemyType.scoutDrone, 'number': 6},
			{'time': 3, 'type': Game.enemyType.missileTruck, 'number': 3},
			{'time': 3, 'type': Game.enemyType.attackHelicopter, 'number': 3},
			{'time': 4, 'type': Game.enemyType.suicideTruck, 'number': 4},
			{'time': 4, 'type': Game.enemyType.mediumTank, 'number': 7},
			{'time': 5, 'type': Game.enemyType.missileTruck, 'number': 4},
			{'time': 5, 'type': Game.enemyType.assaultBuggy, 'number': 16},
			{'time': 6, 'type': Game.enemyType.heavyTank, 'number': 5},
			{'time': 6, 'type': Game.enemyType.attackHelicopter, 'number': 4},
			{'time': 7, 'type': Game.enemyType.scoutDrone, 'number': 8},
			{'time': 7, 'type': Game.enemyType.suicideTruck, 'number': 5},
			{'time': 8, 'type': Game.enemyType.mediumTank, 'number': 8},
			{'time': 8, 'type': Game.enemyType.missileTruck, 'number': 4},
			{'time': 9, 'type': Game.enemyType.heavyTank, 'number': 6},
			{'time': 10, 'type': Game.enemyType.attackHelicopter, 'number': 5},
			{'time': 11, 'type': Game.enemyType.suicideTruck, 'number': 6},
			{'time': 12, 'type': Game.enemyType.missileTruck, 'number': 5},
			{'time': 13, 'type': Game.enemyType.heavyTank, 'number': 7},
			{'time': 14, 'type': Game.enemyType.attackHelicopter, 'number': 5}
		]
	},
	{
		'name': '12',
		"id": 12,
		'category': '高压挑战',
		'description': '应对持续的多类型复合波次',
		'wave': 15,
		'health': 9,
		'money': 550,
		'scene': 'res://scene/level/level_1.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.assaultBuggy, 'number': 16},
			{'time': 1, 'type': Game.enemyType.scoutDrone, 'number': 6},
			{'time': 2, 'type': Game.enemyType.mediumTank, 'number': 6},
			{'time': 2, 'type': Game.enemyType.heavyTank, 'number': 3},
			{'time': 3, 'type': Game.enemyType.missileTruck, 'number': 4},
			{'time': 3, 'type': Game.enemyType.attackHelicopter, 'number': 3},
			{'time': 4, 'type': Game.enemyType.suicideTruck, 'number': 5},
			{'time': 4, 'type': Game.enemyType.assaultBuggy, 'number': 18},
			{'time': 5, 'type': Game.enemyType.heavyTank, 'number': 6},
			{'time': 5, 'type': Game.enemyType.mediumTank, 'number': 8},
			{'time': 6, 'type': Game.enemyType.missileTruck, 'number': 5},
			{'time': 6, 'type': Game.enemyType.scoutDrone, 'number': 8},
			{'time': 7, 'type': Game.enemyType.attackHelicopter, 'number': 4},
			{'time': 7, 'type': Game.enemyType.suicideTruck, 'number': 6},
			{'time': 8, 'type': Game.enemyType.heavyTank, 'number': 7},
			{'time': 8, 'type': Game.enemyType.assaultBuggy, 'number': 20},
			{'time': 9, 'type': Game.enemyType.missileTruck, 'number': 5},
			{'time': 10, 'type': Game.enemyType.attackHelicopter, 'number': 5},
			{'time': 11, 'type': Game.enemyType.mediumTank, 'number': 10},
			{'time': 12, 'type': Game.enemyType.suicideTruck, 'number': 7},
			{'time': 13, 'type': Game.enemyType.heavyTank, 'number': 8},
			{'time': 14, 'type': Game.enemyType.missileTruck, 'number': 6},
			{'time': 15, 'type': Game.enemyType.attackHelicopter, 'number': 6}
		]
	},
	{
		'name': '13',
		"id": 13,
		'category': '高压挑战',
		'description': '远程火力和重型单位同步增强',
		'wave': 16,
		'health': 9,
		'money': 600,
		'scene': 'res://scene/level/level_1.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.mediumTank, 'number': 7},
			{'time': 1, 'type': Game.enemyType.assaultBuggy, 'number': 18},
			{'time': 2, 'type': Game.enemyType.missileTruck, 'number': 4},
			{'time': 2, 'type': Game.enemyType.scoutDrone, 'number': 8},
			{'time': 3, 'type': Game.enemyType.heavyTank, 'number': 5},
			{'time': 3, 'type': Game.enemyType.attackHelicopter, 'number': 4},
			{'time': 4, 'type': Game.enemyType.suicideTruck, 'number': 6},
			{'time': 4, 'type': Game.enemyType.mediumTank, 'number': 9},
			{'time': 5, 'type': Game.enemyType.missileTruck, 'number': 5},
			{'time': 5, 'type': Game.enemyType.assaultBuggy, 'number': 20},
			{'time': 6, 'type': Game.enemyType.heavyTank, 'number': 7},
			{'time': 6, 'type': Game.enemyType.scoutDrone, 'number': 10},
			{'time': 7, 'type': Game.enemyType.attackHelicopter, 'number': 5},
			{'time': 7, 'type': Game.enemyType.suicideTruck, 'number': 7},
			{'time': 8, 'type': Game.enemyType.missileTruck, 'number': 6},
			{'time': 8, 'type': Game.enemyType.mediumTank, 'number': 10},
			{'time': 9, 'type': Game.enemyType.heavyTank, 'number': 8},
			{'time': 10, 'type': Game.enemyType.attackHelicopter, 'number': 6},
			{'time': 11, 'type': Game.enemyType.suicideTruck, 'number': 8},
			{'time': 12, 'type': Game.enemyType.missileTruck, 'number': 7},
			{'time': 13, 'type': Game.enemyType.heavyTank, 'number': 9},
			{'time': 14, 'type': Game.enemyType.attackHelicopter, 'number': 7},
			{'time': 15, 'type': Game.enemyType.mediumTank, 'number': 12},
			{'time': 16, 'type': Game.enemyType.missileTruck, 'number': 8}
		]
	},
	{
		'name': '14',
		"id": 14,
		'category': '高压挑战',
		'description': '高数量、高强度的综合防守',
		'wave': 17,
		'health': 8,
		'money': 650,
		'scene': 'res://scene/level/level_1.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.assaultBuggy, 'number': 20},
			{'time': 1, 'type': Game.enemyType.scoutDrone, 'number': 8},
			{'time': 2, 'type': Game.enemyType.heavyTank, 'number': 6},
			{'time': 2, 'type': Game.enemyType.mediumTank, 'number': 8},
			{'time': 3, 'type': Game.enemyType.missileTruck, 'number': 5},
			{'time': 3, 'type': Game.enemyType.attackHelicopter, 'number': 5},
			{'time': 4, 'type': Game.enemyType.suicideTruck, 'number': 7},
			{'time': 4, 'type': Game.enemyType.assaultBuggy, 'number': 22},
			{'time': 5, 'type': Game.enemyType.missileTruck, 'number': 6},
			{'time': 5, 'type': Game.enemyType.heavyTank, 'number': 8},
			{'time': 6, 'type': Game.enemyType.scoutDrone, 'number': 12},
			{'time': 6, 'type': Game.enemyType.attackHelicopter, 'number': 6},
			{'time': 7, 'type': Game.enemyType.mediumTank, 'number': 12},
			{'time': 7, 'type': Game.enemyType.suicideTruck, 'number': 8},
			{'time': 8, 'type': Game.enemyType.missileTruck, 'number': 7},
			{'time': 8, 'type': Game.enemyType.heavyTank, 'number': 9},
			{'time': 9, 'type': Game.enemyType.attackHelicopter, 'number': 7},
			{'time': 10, 'type': Game.enemyType.assaultBuggy, 'number': 24},
			{'time': 11, 'type': Game.enemyType.suicideTruck, 'number': 9},
			{'time': 12, 'type': Game.enemyType.missileTruck, 'number': 8},
			{'time': 13, 'type': Game.enemyType.heavyTank, 'number': 10},
			{'time': 14, 'type': Game.enemyType.attackHelicopter, 'number': 8},
			{'time': 15, 'type': Game.enemyType.mediumTank, 'number': 14},
			{'time': 16, 'type': Game.enemyType.missileTruck, 'number': 9},
			{'time': 17, 'type': Game.enemyType.heavyTank, 'number': 11}
		]
	},
	{
		'name': '15',
		"id": 15,
		'category': '高压挑战',
		'description': '最终关卡，迎接最大规模的敌群',
		'wave': 18,
		'health': 8,
		'money': 720,
		'scene': 'res://scene/level/level_1.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.mediumTank, 'number': 9},
			{'time': 1, 'type': Game.enemyType.assaultBuggy, 'number': 22},
			{'time': 2, 'type': Game.enemyType.missileTruck, 'number': 6},
			{'time': 2, 'type': Game.enemyType.scoutDrone, 'number': 10},
			{'time': 3, 'type': Game.enemyType.heavyTank, 'number': 7},
			{'time': 3, 'type': Game.enemyType.attackHelicopter, 'number': 6},
			{'time': 4, 'type': Game.enemyType.suicideTruck, 'number': 8},
			{'time': 4, 'type': Game.enemyType.assaultBuggy, 'number': 24},
			{'time': 5, 'type': Game.enemyType.missileTruck, 'number': 7},
			{'time': 5, 'type': Game.enemyType.mediumTank, 'number': 12},
			{'time': 6, 'type': Game.enemyType.heavyTank, 'number': 9},
			{'time': 6, 'type': Game.enemyType.scoutDrone, 'number': 14},
			{'time': 7, 'type': Game.enemyType.attackHelicopter, 'number': 7},
			{'time': 7, 'type': Game.enemyType.suicideTruck, 'number': 9},
			{'time': 8, 'type': Game.enemyType.missileTruck, 'number': 8},
			{'time': 8, 'type': Game.enemyType.heavyTank, 'number': 10},
			{'time': 9, 'type': Game.enemyType.attackHelicopter, 'number': 8},
			{'time': 10, 'type': Game.enemyType.assaultBuggy, 'number': 26},
			{'time': 11, 'type': Game.enemyType.suicideTruck, 'number': 10},
			{'time': 12, 'type': Game.enemyType.missileTruck, 'number': 9},
			{'time': 13, 'type': Game.enemyType.heavyTank, 'number': 12},
			{'time': 14, 'type': Game.enemyType.attackHelicopter, 'number': 9},
			{'time': 15, 'type': Game.enemyType.mediumTank, 'number': 16},
			{'time': 16, 'type': Game.enemyType.missileTruck, 'number': 10},
			{'time': 17, 'type': Game.enemyType.suicideTruck, 'number': 12},
			{'time': 18, 'type': Game.enemyType.heavyTank, 'number': 14}
		]
	},
]

var enemyScenes = {
	Game.enemyType.miniTank: preload("res://scene/miniTank.tscn"),
	Game.enemyType.mediumTank: preload("res://scene/medium_tank.tscn"),
	Game.enemyType.heavyTank: preload("res://scene/heavy_tank.tscn"),
	Game.enemyType.armoredTank: preload("res://scene/armored_tank.tscn"),
	Game.enemyType.assaultBuggy: preload("res://scene/assault_buggy.tscn"),
	Game.enemyType.medic: preload("res://scene/medic.tscn"),
	Game.enemyType.suicideTruck: preload("res://scene/suicide_truck.tscn"),
	Game.enemyType.missileTruck: preload("res://scene/missile_truck.tscn"),
	Game.enemyType.scoutDrone: preload("res://scene/scout_drone.tscn"),
	Game.enemyType.attackHelicopter: preload("res://scene/attack_helicopter.tscn")
}
