extends Node

const TileSize = 64  #网格大小

# 当前选中的关卡ID（由 level_select 点击时设置，map 读取后加载对应场景）
var currentStageId: int = 1

#关卡的数据
var allStage = [
	{
		'name': '1',
		"id": 1,
		'category': '基础教学',
		'description': '熟悉建造防御塔和开始波次',
		'wave': 3,
		'health': 20,
		'money': 150,
		'scene': 'res://scene/level/level_1.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.miniTank, 'number': 2},
			{'time': 2, 'type': Game.enemyType.miniTank, 'number': 3},
			{'time': 3, 'type': Game.enemyType.miniTank, 'number': 4}
		]
	},
	{
		'name': '2',
		"id": 2,
		'category': '基础教学',
		'description': '练习目标选择和应对快速敌人',
		'wave': 4,
		'health': 20,
		'money': 180,
		'scene': 'res://scene/level/level_1.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.miniTank, 'number': 3},
			{'time': 2, 'type': Game.enemyType.miniTank, 'number': 4},
			{'time': 2, 'type': Game.enemyType.assaultBuggy, 'number': 1},
			{'time': 3, 'type': Game.enemyType.miniTank, 'number': 5},
			{'time': 3, 'type': Game.enemyType.assaultBuggy, 'number': 2},
			{'time': 4, 'type': Game.enemyType.miniTank, 'number': 6},
			{'time': 4, 'type': Game.enemyType.assaultBuggy, 'number': 2}
		]
	},
	{
		'name': '3',
		"id": 3,
		'category': '基础教学',
		'description': '完成基础防守并认识重型目标',
		'wave': 5,
		'health': 18,
		'money': 220,
		'scene': 'res://scene/level/level_1.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.miniTank, 'number': 4},
			{'time': 2, 'type': Game.enemyType.miniTank, 'number': 5},
			{'time': 2, 'type': Game.enemyType.mediumTank, 'number': 1},
			{'time': 3, 'type': Game.enemyType.miniTank, 'number': 6},
			{'time': 3, 'type': Game.enemyType.mediumTank, 'number': 1},
			{'time': 4, 'type': Game.enemyType.assaultBuggy, 'number': 3},
			{'time': 4, 'type': Game.enemyType.mediumTank, 'number': 2},
			{'time': 5, 'type': Game.enemyType.heavyTank, 'number': 1}
		]
	},
	{
		'name': '4',
		"id": 4,
		'category': '进阶挑战',
		'description': '应对快速敌人和自爆威胁',
		'wave': 7,
		'health': 16,
		'money': 190,
		'scene': 'res://scene/level/level_1.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.assaultBuggy, 'number': 5},
			{'time': 1, 'type': Game.enemyType.miniTank, 'number': 4},
			{'time': 2, 'type': Game.enemyType.assaultBuggy, 'number': 7},
			{'time': 2, 'type': Game.enemyType.mediumTank, 'number': 1},
			{'time': 3, 'type': Game.enemyType.miniTank, 'number': 10},
			{'time': 3, 'type': Game.enemyType.mediumTank, 'number': 2},
			{'time': 4, 'type': Game.enemyType.suicideTruck, 'number': 1},
			{'time': 4, 'type': Game.enemyType.assaultBuggy, 'number': 8},
			{'time': 5, 'type': Game.enemyType.heavyTank, 'number': 2},
			{'time': 5, 'type': Game.enemyType.assaultBuggy, 'number': 6},
			{'time': 6, 'type': Game.enemyType.suicideTruck, 'number': 2},
			{'time': 6, 'type': Game.enemyType.mediumTank, 'number': 3},
			{'time': 7, 'type': Game.enemyType.heavyTank, 'number': 2},
			{'time': 7, 'type': Game.enemyType.assaultBuggy, 'number': 10}
		]
	},
	{
		'name': '5',
		"id": 5,
		'category': '进阶挑战',
		'description': '学习处理远程导弹攻击',
		'wave': 8,
		'health': 14,
		'money': 230,
		'scene': 'res://scene/level/level_1.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.miniTank, 'number': 6},
			{'time': 1, 'type': Game.enemyType.mediumTank, 'number': 1},
			{'time': 2, 'type': Game.enemyType.missileTruck, 'number': 1},
			{'time': 2, 'type': Game.enemyType.assaultBuggy, 'number': 5},
			{'time': 3, 'type': Game.enemyType.mediumTank, 'number': 3},
			{'time': 3, 'type': Game.enemyType.miniTank, 'number': 8},
			{'time': 4, 'type': Game.enemyType.missileTruck, 'number': 1},
			{'time': 4, 'type': Game.enemyType.heavyTank, 'number': 1},
			{'time': 5, 'type': Game.enemyType.mediumTank, 'number': 4},
			{'time': 5, 'type': Game.enemyType.assaultBuggy, 'number': 8},
			{'time': 6, 'type': Game.enemyType.missileTruck, 'number': 2},
			{'time': 6, 'type': Game.enemyType.heavyTank, 'number': 2},
			{'time': 7, 'type': Game.enemyType.suicideTruck, 'number': 2},
			{'time': 7, 'type': Game.enemyType.mediumTank, 'number': 5},
			{'time': 8, 'type': Game.enemyType.missileTruck, 'number': 2},
			{'time': 8, 'type': Game.enemyType.heavyTank, 'number': 3}
		]
	},
	{
		'name': '6',
		"id": 6,
		'category': '进阶挑战',
		'description': '首次面对完整的空地混合进攻',
		'wave': 9,
		'health': 12,
		'money': 280,
		'scene': 'res://scene/level/level_1.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.assaultBuggy, 'number': 6},
			{'time': 1, 'type': Game.enemyType.scoutDrone, 'number': 2},
			{'time': 2, 'type': Game.enemyType.miniTank, 'number': 8},
			{'time': 2, 'type': Game.enemyType.mediumTank, 'number': 2},
			{'time': 3, 'type': Game.enemyType.attackHelicopter, 'number': 1},
			{'time': 3, 'type': Game.enemyType.assaultBuggy, 'number': 8},
			{'time': 4, 'type': Game.enemyType.missileTruck, 'number': 1},
			{'time': 4, 'type': Game.enemyType.heavyTank, 'number': 2},
			{'time': 5, 'type': Game.enemyType.attackHelicopter, 'number': 2},
			{'time': 5, 'type': Game.enemyType.mediumTank, 'number': 4},
			{'time': 6, 'type': Game.enemyType.suicideTruck, 'number': 2},
			{'time': 6, 'type': Game.enemyType.scoutDrone, 'number': 4},
			{'time': 7, 'type': Game.enemyType.missileTruck, 'number': 2},
			{'time': 7, 'type': Game.enemyType.heavyTank, 'number': 3},
			{'time': 8, 'type': Game.enemyType.attackHelicopter, 'number': 2},
			{'time': 8, 'type': Game.enemyType.mediumTank, 'number': 5},
			{'time': 9, 'type': Game.enemyType.missileTruck, 'number': 3},
			{'time': 9, 'type': Game.enemyType.heavyTank, 'number': 4}
		]
	},
	{
		'name': '7',
		"id": 7,
		'category': '战术挑战',
		'description': '多方向混合敌人持续施压',
		'wave': 10,
		'health': 12,
		'money': 320,
		'scene': 'res://scene/level/level_1.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.miniTank, 'number': 8},
			{'time': 1, 'type': Game.enemyType.scoutDrone, 'number': 2},
			{'time': 2, 'type': Game.enemyType.assaultBuggy, 'number': 8},
			{'time': 2, 'type': Game.enemyType.mediumTank, 'number': 3},
			{'time': 3, 'type': Game.enemyType.attackHelicopter, 'number': 1},
			{'time': 3, 'type': Game.enemyType.miniTank, 'number': 10},
			{'time': 4, 'type': Game.enemyType.missileTruck, 'number': 1},
			{'time': 4, 'type': Game.enemyType.assaultBuggy, 'number': 10},
			{'time': 5, 'type': Game.enemyType.heavyTank, 'number': 2},
			{'time': 5, 'type': Game.enemyType.mediumTank, 'number': 4},
			{'time': 6, 'type': Game.enemyType.attackHelicopter, 'number': 2},
			{'time': 6, 'type': Game.enemyType.scoutDrone, 'number': 4},
			{'time': 7, 'type': Game.enemyType.suicideTruck, 'number': 2},
			{'time': 7, 'type': Game.enemyType.missileTruck, 'number': 2},
			{'time': 8, 'type': Game.enemyType.heavyTank, 'number': 3},
			{'time': 8, 'type': Game.enemyType.assaultBuggy, 'number': 12},
			{'time': 9, 'type': Game.enemyType.attackHelicopter, 'number': 2},
			{'time': 10, 'type': Game.enemyType.missileTruck, 'number': 3}
		]
	},
	{
		'name': '8',
		"id": 8,
		'category': '战术挑战',
		'description': '提高空中单位和远程单位密度',
		'wave': 11,
		'health': 11,
		'money': 360,
		'scene': 'res://scene/level/level_1.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.assaultBuggy, 'number': 10},
			{'time': 1, 'type': Game.enemyType.mediumTank, 'number': 2},
			{'time': 2, 'type': Game.enemyType.scoutDrone, 'number': 4},
			{'time': 2, 'type': Game.enemyType.miniTank, 'number': 10},
			{'time': 3, 'type': Game.enemyType.heavyTank, 'number': 2},
			{'time': 3, 'type': Game.enemyType.assaultBuggy, 'number': 8},
			{'time': 4, 'type': Game.enemyType.missileTruck, 'number': 2},
			{'time': 4, 'type': Game.enemyType.mediumTank, 'number': 4},
			{'time': 5, 'type': Game.enemyType.attackHelicopter, 'number': 2},
			{'time': 5, 'type': Game.enemyType.scoutDrone, 'number': 5},
			{'time': 6, 'type': Game.enemyType.suicideTruck, 'number': 2},
			{'time': 6, 'type': Game.enemyType.heavyTank, 'number': 3},
			{'time': 7, 'type': Game.enemyType.missileTruck, 'number': 2},
			{'time': 7, 'type': Game.enemyType.attackHelicopter, 'number': 3},
			{'time': 8, 'type': Game.enemyType.mediumTank, 'number': 5},
			{'time': 8, 'type': Game.enemyType.assaultBuggy, 'number': 12},
			{'time': 9, 'type': Game.enemyType.heavyTank, 'number': 4},
			{'time': 10, 'type': Game.enemyType.suicideTruck, 'number': 3},
			{'time': 11, 'type': Game.enemyType.missileTruck, 'number': 3}
		]
	},
	{
		'name': '9',
		"id": 9,
		'category': '战术挑战',
		'description': '在高数量敌群中保持防线',
		'wave': 12,
		'health': 11,
		'money': 400,
		'scene': 'res://scene/level/level_1.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.miniTank, 'number': 12},
			{'time': 1, 'type': Game.enemyType.mediumTank, 'number': 3},
			{'time': 2, 'type': Game.enemyType.missileTruck, 'number': 2},
			{'time': 2, 'type': Game.enemyType.assaultBuggy, 'number': 10},
			{'time': 3, 'type': Game.enemyType.heavyTank, 'number': 3},
			{'time': 3, 'type': Game.enemyType.scoutDrone, 'number': 5},
			{'time': 4, 'type': Game.enemyType.attackHelicopter, 'number': 2},
			{'time': 4, 'type': Game.enemyType.mediumTank, 'number': 5},
			{'time': 5, 'type': Game.enemyType.suicideTruck, 'number': 3},
			{'time': 5, 'type': Game.enemyType.assaultBuggy, 'number': 12},
			{'time': 6, 'type': Game.enemyType.missileTruck, 'number': 3},
			{'time': 6, 'type': Game.enemyType.heavyTank, 'number': 4},
			{'time': 7, 'type': Game.enemyType.attackHelicopter, 'number': 3},
			{'time': 7, 'type': Game.enemyType.scoutDrone, 'number': 6},
			{'time': 8, 'type': Game.enemyType.mediumTank, 'number': 6},
			{'time': 8, 'type': Game.enemyType.assaultBuggy, 'number': 14},
			{'time': 9, 'type': Game.enemyType.suicideTruck, 'number': 4},
			{'time': 10, 'type': Game.enemyType.missileTruck, 'number': 3},
			{'time': 11, 'type': Game.enemyType.heavyTank, 'number': 5},
			{'time': 12, 'type': Game.enemyType.attackHelicopter, 'number': 4}
		]
	},
	{
		'name': '10',
		"id": 10,
		'category': '战术挑战',
		'description': '综合考验地面、空中和远程防守',
		'wave': 13,
		'health': 10,
		'money': 450,
		'scene': 'res://scene/level/level_1.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.assaultBuggy, 'number': 12},
			{'time': 1, 'type': Game.enemyType.scoutDrone, 'number': 4},
			{'time': 2, 'type': Game.enemyType.mediumTank, 'number': 4},
			{'time': 2, 'type': Game.enemyType.miniTank, 'number': 12},
			{'time': 3, 'type': Game.enemyType.missileTruck, 'number': 2},
			{'time': 3, 'type': Game.enemyType.attackHelicopter, 'number': 2},
			{'time': 4, 'type': Game.enemyType.heavyTank, 'number': 4},
			{'time': 4, 'type': Game.enemyType.assaultBuggy, 'number': 12},
			{'time': 5, 'type': Game.enemyType.suicideTruck, 'number': 3},
			{'time': 5, 'type': Game.enemyType.mediumTank, 'number': 6},
			{'time': 6, 'type': Game.enemyType.missileTruck, 'number': 3},
			{'time': 6, 'type': Game.enemyType.scoutDrone, 'number': 6},
			{'time': 7, 'type': Game.enemyType.attackHelicopter, 'number': 3},
			{'time': 7, 'type': Game.enemyType.heavyTank, 'number': 5},
			{'time': 8, 'type': Game.enemyType.suicideTruck, 'number': 4},
			{'time': 8, 'type': Game.enemyType.assaultBuggy, 'number': 16},
			{'time': 9, 'type': Game.enemyType.missileTruck, 'number': 4},
			{'time': 10, 'type': Game.enemyType.attackHelicopter, 'number': 4},
			{'time': 11, 'type': Game.enemyType.heavyTank, 'number': 6},
			{'time': 12, 'type': Game.enemyType.mediumTank, 'number': 8},
			{'time': 13, 'type': Game.enemyType.missileTruck, 'number': 4}
		]
	},
	{
		'name': '11',
		"id": 11,
		'category': '高压挑战',
		'description': '高密度重型单位开始连续出现',
		'wave': 14,
		'health': 10,
		'money': 500,
		'scene': 'res://scene/level/level_1.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.mediumTank, 'number': 5},
			{'time': 1, 'type': Game.enemyType.assaultBuggy, 'number': 14},
			{'time': 2, 'type': Game.enemyType.heavyTank, 'number': 4},
			{'time': 2, 'type': Game.enemyType.scoutDrone, 'number': 6},
			{'time': 3, 'type': Game.enemyType.missileTruck, 'number': 3},
			{'time': 3, 'type': Game.enemyType.attackHelicopter, 'number': 3},
			{'time': 4, 'type': Game.enemyType.suicideTruck, 'number': 4},
			{'time': 4, 'type': Game.enemyType.mediumTank, 'number': 7},
			{'time': 5, 'type': Game.enemyType.missileTruck, 'number': 4},
			{'time': 5, 'type': Game.enemyType.assaultBuggy, 'number': 16},
			{'time': 6, 'type': Game.enemyType.heavyTank, 'number': 5},
			{'time': 6, 'type': Game.enemyType.attackHelicopter, 'number': 4},
			{'time': 7, 'type': Game.enemyType.scoutDrone, 'number': 8},
			{'time': 7, 'type': Game.enemyType.suicideTruck, 'number': 5},
			{'time': 8, 'type': Game.enemyType.mediumTank, 'number': 8},
			{'time': 8, 'type': Game.enemyType.missileTruck, 'number': 4},
			{'time': 9, 'type': Game.enemyType.heavyTank, 'number': 6},
			{'time': 10, 'type': Game.enemyType.attackHelicopter, 'number': 5},
			{'time': 11, 'type': Game.enemyType.suicideTruck, 'number': 6},
			{'time': 12, 'type': Game.enemyType.missileTruck, 'number': 5},
			{'time': 13, 'type': Game.enemyType.heavyTank, 'number': 7},
			{'time': 14, 'type': Game.enemyType.attackHelicopter, 'number': 5}
		]
	},
	{
		'name': '12',
		"id": 12,
		'category': '高压挑战',
		'description': '应对持续的多类型复合波次',
		'wave': 15,
		'health': 9,
		'money': 550,
		'scene': 'res://scene/level/level_1.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.assaultBuggy, 'number': 16},
			{'time': 1, 'type': Game.enemyType.scoutDrone, 'number': 6},
			{'time': 2, 'type': Game.enemyType.mediumTank, 'number': 6},
			{'time': 2, 'type': Game.enemyType.heavyTank, 'number': 3},
			{'time': 3, 'type': Game.enemyType.missileTruck, 'number': 4},
			{'time': 3, 'type': Game.enemyType.attackHelicopter, 'number': 3},
			{'time': 4, 'type': Game.enemyType.suicideTruck, 'number': 5},
			{'time': 4, 'type': Game.enemyType.assaultBuggy, 'number': 18},
			{'time': 5, 'type': Game.enemyType.heavyTank, 'number': 6},
			{'time': 5, 'type': Game.enemyType.mediumTank, 'number': 8},
			{'time': 6, 'type': Game.enemyType.missileTruck, 'number': 5},
			{'time': 6, 'type': Game.enemyType.scoutDrone, 'number': 8},
			{'time': 7, 'type': Game.enemyType.attackHelicopter, 'number': 4},
			{'time': 7, 'type': Game.enemyType.suicideTruck, 'number': 6},
			{'time': 8, 'type': Game.enemyType.heavyTank, 'number': 7},
			{'time': 8, 'type': Game.enemyType.assaultBuggy, 'number': 20},
			{'time': 9, 'type': Game.enemyType.missileTruck, 'number': 5},
			{'time': 10, 'type': Game.enemyType.attackHelicopter, 'number': 5},
			{'time': 11, 'type': Game.enemyType.mediumTank, 'number': 10},
			{'time': 12, 'type': Game.enemyType.suicideTruck, 'number': 7},
			{'time': 13, 'type': Game.enemyType.heavyTank, 'number': 8},
			{'time': 14, 'type': Game.enemyType.missileTruck, 'number': 6},
			{'time': 15, 'type': Game.enemyType.attackHelicopter, 'number': 6}
		]
	},
	{
		'name': '13',
		"id": 13,
		'category': '高压挑战',
		'description': '远程火力和重型单位同步增强',
		'wave': 16,
		'health': 9,
		'money': 600,
		'scene': 'res://scene/level/level_1.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.mediumTank, 'number': 7},
			{'time': 1, 'type': Game.enemyType.assaultBuggy, 'number': 18},
			{'time': 2, 'type': Game.enemyType.missileTruck, 'number': 4},
			{'time': 2, 'type': Game.enemyType.scoutDrone, 'number': 8},
			{'time': 3, 'type': Game.enemyType.heavyTank, 'number': 5},
			{'time': 3, 'type': Game.enemyType.attackHelicopter, 'number': 4},
			{'time': 4, 'type': Game.enemyType.suicideTruck, 'number': 6},
			{'time': 4, 'type': Game.enemyType.mediumTank, 'number': 9},
			{'time': 5, 'type': Game.enemyType.missileTruck, 'number': 5},
			{'time': 5, 'type': Game.enemyType.assaultBuggy, 'number': 20},
			{'time': 6, 'type': Game.enemyType.heavyTank, 'number': 7},
			{'time': 6, 'type': Game.enemyType.scoutDrone, 'number': 10},
			{'time': 7, 'type': Game.enemyType.attackHelicopter, 'number': 5},
			{'time': 7, 'type': Game.enemyType.suicideTruck, 'number': 7},
			{'time': 8, 'type': Game.enemyType.missileTruck, 'number': 6},
			{'time': 8, 'type': Game.enemyType.mediumTank, 'number': 10},
			{'time': 9, 'type': Game.enemyType.heavyTank, 'number': 8},
			{'time': 10, 'type': Game.enemyType.attackHelicopter, 'number': 6},
			{'time': 11, 'type': Game.enemyType.suicideTruck, 'number': 8},
			{'time': 12, 'type': Game.enemyType.missileTruck, 'number': 7},
			{'time': 13, 'type': Game.enemyType.heavyTank, 'number': 9},
			{'time': 14, 'type': Game.enemyType.attackHelicopter, 'number': 7},
			{'time': 15, 'type': Game.enemyType.mediumTank, 'number': 12},
			{'time': 16, 'type': Game.enemyType.missileTruck, 'number': 8}
		]
	},
	{
		'name': '14',
		"id": 14,
		'category': '高压挑战',
		'description': '高数量、高强度的综合防守',
		'wave': 17,
		'health': 8,
		'money': 650,
		'scene': 'res://scene/level/level_1.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.assaultBuggy, 'number': 20},
			{'time': 1, 'type': Game.enemyType.scoutDrone, 'number': 8},
			{'time': 2, 'type': Game.enemyType.heavyTank, 'number': 6},
			{'time': 2, 'type': Game.enemyType.mediumTank, 'number': 8},
			{'time': 3, 'type': Game.enemyType.missileTruck, 'number': 5},
			{'time': 3, 'type': Game.enemyType.attackHelicopter, 'number': 5},
			{'time': 4, 'type': Game.enemyType.suicideTruck, 'number': 7},
			{'time': 4, 'type': Game.enemyType.assaultBuggy, 'number': 22},
			{'time': 5, 'type': Game.enemyType.missileTruck, 'number': 6},
			{'time': 5, 'type': Game.enemyType.heavyTank, 'number': 8},
			{'time': 6, 'type': Game.enemyType.scoutDrone, 'number': 12},
			{'time': 6, 'type': Game.enemyType.attackHelicopter, 'number': 6},
			{'time': 7, 'type': Game.enemyType.mediumTank, 'number': 12},
			{'time': 7, 'type': Game.enemyType.suicideTruck, 'number': 8},
			{'time': 8, 'type': Game.enemyType.missileTruck, 'number': 7},
			{'time': 8, 'type': Game.enemyType.heavyTank, 'number': 9},
			{'time': 9, 'type': Game.enemyType.attackHelicopter, 'number': 7},
			{'time': 10, 'type': Game.enemyType.assaultBuggy, 'number': 24},
			{'time': 11, 'type': Game.enemyType.suicideTruck, 'number': 9},
			{'time': 12, 'type': Game.enemyType.missileTruck, 'number': 8},
			{'time': 13, 'type': Game.enemyType.heavyTank, 'number': 10},
			{'time': 14, 'type': Game.enemyType.attackHelicopter, 'number': 8},
			{'time': 15, 'type': Game.enemyType.mediumTank, 'number': 14},
			{'time': 16, 'type': Game.enemyType.missileTruck, 'number': 9},
			{'time': 17, 'type': Game.enemyType.heavyTank, 'number': 11}
		]
	},
	{
		'name': '15',
		"id": 15,
		'category': '高压挑战',
		'description': '最终关卡，迎接最大规模的敌群',
		'wave': 18,
		'health': 8,
		'money': 720,
		'scene': 'res://scene/level/level_1.tscn',
		"enemySpawner": [
			{'time': 1, 'type': Game.enemyType.mediumTank, 'number': 9},
			{'time': 1, 'type': Game.enemyType.assaultBuggy, 'number': 22},
			{'time': 2, 'type': Game.enemyType.missileTruck, 'number': 6},
			{'time': 2, 'type': Game.enemyType.scoutDrone, 'number': 10},
			{'time': 3, 'type': Game.enemyType.heavyTank, 'number': 7},
			{'time': 3, 'type': Game.enemyType.attackHelicopter, 'number': 6},
			{'time': 4, 'type': Game.enemyType.suicideTruck, 'number': 8},
			{'time': 4, 'type': Game.enemyType.assaultBuggy, 'number': 24},
			{'time': 5, 'type': Game.enemyType.missileTruck, 'number': 7},
			{'time': 5, 'type': Game.enemyType.mediumTank, 'number': 12},
			{'time': 6, 'type': Game.enemyType.heavyTank, 'number': 9},
			{'time': 6, 'type': Game.enemyType.scoutDrone, 'number': 14},
			{'time': 7, 'type': Game.enemyType.attackHelicopter, 'number': 7},
			{'time': 7, 'type': Game.enemyType.suicideTruck, 'number': 9},
			{'time': 8, 'type': Game.enemyType.missileTruck, 'number': 8},
			{'time': 8, 'type': Game.enemyType.heavyTank, 'number': 10},
			{'time': 9, 'type': Game.enemyType.attackHelicopter, 'number': 8},
			{'time': 10, 'type': Game.enemyType.assaultBuggy, 'number': 26},
			{'time': 11, 'type': Game.enemyType.suicideTruck, 'number': 10},
			{'time': 12, 'type': Game.enemyType.missileTruck, 'number': 9},
			{'time': 13, 'type': Game.enemyType.heavyTank, 'number': 12},
			{'time': 14, 'type': Game.enemyType.attackHelicopter, 'number': 9},
			{'time': 15, 'type': Game.enemyType.mediumTank, 'number': 16},
			{'time': 16, 'type': Game.enemyType.missileTruck, 'number': 10},
			{'time': 17, 'type': Game.enemyType.suicideTruck, 'number': 12},
			{'time': 18, 'type': Game.enemyType.heavyTank, 'number': 14}
		]
	},
]

var enemyScenes = {
	Game.enemyType.miniTank: preload("res://scene/miniTank.tscn"),
	Game.enemyType.mediumTank: preload("res://scene/medium_tank.tscn"),
	Game.enemyType.heavyTank: preload("res://scene/heavy_tank.tscn"),
	Game.enemyType.armoredTank: preload("res://scene/armored_tank.tscn"),
	Game.enemyType.assaultBuggy: preload("res://scene/assault_buggy.tscn"),
	Game.enemyType.medic: preload("res://scene/medic.tscn"),
	Game.enemyType.suicideTruck: preload("res://scene/suicide_truck.tscn"),
	Game.enemyType.missileTruck: preload("res://scene/missile_truck.tscn"),
	Game.enemyType.scoutDrone: preload("res://scene/scout_drone.tscn"),
	Game.enemyType.attackHelicopter: preload("res://scene/attack_helicopter.tscn")
}
